import "dotenv/config";
import { createHash, randomUUID, randomBytes } from "node:crypto";
import { afterAll, describe, expect, it } from "vitest";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@/generated/prisma/client";
import { BookingDrafts } from "@/modules/booking/application/drafts";
import { aesSecretBox } from "@/modules/notifications/infrastructure/secret-box";
import { bookingNotificationPlanner } from "@/modules/notifications/infrastructure/planner";
import { prismaDrafts } from "@/modules/booking/infrastructure/prisma-drafts";
import { generateManagementToken } from "@/modules/appointments/infrastructure/management-token";
import type { BookingResult } from "@/modules/appointments/application/booking";
import type { DraftRepository } from "@/modules/booking/application/ports";
import type { DraftCommand } from "@/modules/booking/domain/draft";
import { DRAFT_TTL, IDEMPOTENCY_TTL } from "@/modules/booking/domain/draft";
import { profileDetails, serviceDetails } from "../fixtures/catalog";
const connectionString = process.env.TEST_DATABASE_URL;
if (!connectionString || !new URL(connectionString).pathname.endsWith("_test")) throw new Error("Separate TEST_DATABASE_URL required");
const db = new PrismaClient({ adapter: new PrismaPg({ connectionString }) }), repo = prismaDrafts(db, bookingNotificationPlanner(aesSecretBox(randomBytes(32).toString("base64"))));
const hashes: string[] = [], profiles: string[] = [];
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
function value<T>(r: BookingResult<T>): T { if (!r.ok) throw new Error(r.error.code); return r.value; }
async function fixture() {
 let now = Date.parse("2026-10-01T00:00:00Z");
 const api = new BookingDrafts(repo, { now: () => now, id: randomUUID, token: generateManagementToken, hash });
 const created = value(await api.create()); hashes.push(hash(created.cookie));
 const profileId = randomUUID(), serviceId = randomUUID(); profiles.push(profileId);
 await db.advisorProfile.create({ data: { id: profileId, ...profileDetails, status: "ACTIVE", services: { create: { id: serviceId, ...serviceDetails, active: true } }, weeklyAvailability: { create: { id: randomUUID(), weekday: 1, startMinute: 480, endMinute: 720 } } } });
 let version = 0;
 const change = async (command: DraftCommand) => { const d = value(await api.change(created.cookie, version, command)); version = d.version; return d; };
 const ready = async () => {
  await change({ type: "primary", profileId }); await change({ type: "service", serviceId }); await change({ type: "date", date: "2026-10-05" }); await change({ type: "slot", startUtc: "2026-10-05T07:00:00Z" });
  await change({ type: "customer", customer: { firstName: "Test", lastName: "Customer", email: "draft@example.test", phone: "123", address: null, remarks: null } });
  return value(await api.review(created.cookie));
 };
 return { api, created, profileId, serviceId, ready, change, setNow: (n: number) => { now = n; }, now: () => now };
}
afterAll(async () => { await db.$transaction(async tx => {
 await tx.bookingIdempotency.deleteMany({ where: { capabilityHash: { in: hashes } } }); await tx.bookingDraft.deleteMany({ where: { capabilityHash: { in: hashes } } });
 const where = { appointment: { service: { advisorProfileId: { in: profiles } } } };
 await tx.notification.deleteMany({ where });
 await tx.appointmentReservation.deleteMany({ where }); await tx.appointmentGuest.deleteMany({ where }); await tx.appointmentParticipant.deleteMany({ where }); await tx.appointment.deleteMany({ where: { service: { advisorProfileId: { in: profiles } } } });
 await tx.profileRelation.deleteMany({ where: { sourceProfileId: { in: profiles } } }); await tx.weeklyAvailability.deleteMany({ where: { advisorProfileId: { in: profiles } } }); await tx.service.deleteMany({ where: { advisorProfileId: { in: profiles } } }); await tx.advisorProfile.deleteMany({ where: { id: { in: profiles } } });
 }); await db.$disconnect(); });
describe("persisted booking draft and confirmation", () => {
 it("isolates cookie capabilities and never stores the raw cookie", async () => { const a = await fixture(), b = await fixture(); await a.change({ type: "primary", profileId: a.profileId }); expect(value(await b.api.read(b.created.cookie)).payload.primaryProfileId).toBeNull(); expect((await a.api.read(randomUUID())).ok).toBe(false); expect((await a.api.read("z".repeat(43))).ok).toBe(false); const row = await db.bookingDraft.findUniqueOrThrow({ where: { capabilityHash: hash(a.created.cookie) } }); expect(JSON.stringify(row).includes(a.created.cookie)).toBe(false); expect((await a.api.read(row.id)).ok).toBe(false); });
 it("read does not extend TTL, mutation refreshes it, exact boundary expires", async () => { const f = await fixture(), now = f.now(); f.setNow(now + DRAFT_TTL - 1); expect((await f.api.read(f.created.cookie)).ok).toBe(true); await f.change({ type: "primary", profileId: f.profileId }); f.setNow(now + DRAFT_TTL); expect((await f.api.read(f.created.cookie)).ok).toBe(true); f.setNow(now + 2 * DRAFT_TTL - 1); expect((await f.api.read(f.created.cookie)).ok).toBe(false); });
 it("invalidates dependent state and rejects stale versions", async () => { const f = await fixture(); await f.ready(); const changed = await f.change({ type: "participants", participantIds: [f.profileId] }); expect(changed.payload.date).toBeNull(); expect(changed.payload.startUtc).toBeNull(); expect(await f.api.change(f.created.cookie, 0, { type: "primary", profileId: f.profileId })).toMatchObject({ ok: false, error: { code: "CONFLICT" } }); });
 it("defaults required participants and cannot remove them", async () => { const a = await fixture(), b = await fixture(); await db.profileRelation.create({ data: { id: randomUUID(), sourceProfileId: a.profileId, targetProfileId: b.profileId, proposedToClient: false, defaultSelected: true, clientCanRemove: false } }); await a.change({ type: "primary", profileId: a.profileId }); const draft = await a.change({ type: "service", serviceId: a.serviceId }); expect(draft.payload.participantIds).toContain(b.profileId); expect((await a.api.change(a.created.cookie, draft.version, { type: "participants", participantIds: [a.profileId] })).ok).toBe(false); });
 it("commits exactly once on concurrent double submit and deletes draft", async () => { const f = await fixture(), review = await f.ready(), key = randomUUID(); const results = await Promise.all([f.api.confirm(f.created.cookie, key, review.payloadHash, review.version), f.api.confirm(f.created.cookie, key, review.payloadHash, review.version)]); expect(results.every(r => r.ok)).toBe(true); const values = results.map(value); expect(new Set(values.map(v => v.appointmentId)).size).toBe(1); expect(values.filter(v => v.replay)).toHaveLength(1); expect((await f.api.read(f.created.cookie)).ok).toBe(false); const saved = await db.bookingIdempotency.findUniqueOrThrow({ where: { capabilityHash_commandKey: { capabilityHash: hash(f.created.cookie), commandKey: key } } }); expect(JSON.stringify(saved)).not.toContain("rawManagementToken"); expect(saved.expiresAt.getTime()).toBe(f.now() + IDEMPOTENCY_TTL); });
 it("same key with another hash conflicts even after draft deletion", async () => { const f = await fixture(), r = await f.ready(), key = randomUUID(); value(await f.api.confirm(f.created.cookie, key, r.payloadHash, r.version)); expect(await f.api.confirm(f.created.cookie, key, "a".repeat(64), r.version)).toMatchObject({ ok: false, error: { code: "CONFLICT" } }); });
 it("a foreign cookie cannot replay another booking", async () => { const a = await fixture(), b = await fixture(), r = await a.ready(), key = randomUUID(); value(await a.api.confirm(a.created.cookie, key, r.payloadHash, r.version)); expect((await b.api.confirm(b.created.cookie, key, r.payloadHash, r.version)).ok).toBe(false); });
 it("rejects changed review content without partial writes", async () => { const f = await fixture(), r = await f.ready(); const changed = await f.change({ type: "guests", guests: ["g@example.test"] }); expect((await f.api.confirm(f.created.cookie, randomUUID(), r.payloadHash, changed.version)).ok).toBe(false); expect(await db.appointment.count({ where: { serviceId: f.serviceId } })).toBe(0); expect((await f.api.read(f.created.cookie)).ok).toBe(true); });
 it("stale slot leaves the second draft and creates no idempotency record", async () => { const a = await fixture(), b = await fixture(), r = await a.ready(); await b.change({ type: "primary", profileId: a.profileId }); await b.change({ type: "service", serviceId: a.serviceId }); await b.change({ type: "date", date: "2026-10-05" }); await b.change({ type: "slot", startUtc: "2026-10-05T07:00:00Z" }); await b.change({ type: "customer", customer: r.payload.customer! }); const rb = value(await b.api.review(b.created.cookie)); value(await a.api.confirm(a.created.cookie, randomUUID(), r.payloadHash, r.version)); expect(await b.api.confirm(b.created.cookie, randomUUID(), rb.payloadHash, rb.version)).toMatchObject({ ok: false, error: { code: "CONFLICT" } }); expect((await b.api.read(b.created.cookie)).ok).toBe(true); expect(await db.bookingIdempotency.count({ where: { capabilityHash: hash(b.created.cookie) } })).toBe(0); });
 it("idempotency expires at exactly 24h and cannot create another booking", async () => { const f = await fixture(), r = await f.ready(), key = randomUUID(); value(await f.api.confirm(f.created.cookie, key, r.payloadHash, r.version)); f.setNow(f.now() + IDEMPOTENCY_TTL); expect((await f.api.confirm(f.created.cookie, key, r.payloadHash, r.version)).ok).toBe(false); expect(await db.appointment.count({ where: { serviceId: f.serviceId } })).toBe(1); });
 it("rejects direct DB malformed hashes, negative versions and secret result fields", async () => { const f = await fixture(); await expect(db.bookingDraft.updateMany({ where: { capabilityHash: hash(f.created.cookie) }, data: { version: -1 } })).rejects.toThrow(); await expect(db.bookingDraft.updateMany({ where: { capabilityHash: hash(f.created.cookie) }, data: { capabilityHash: "raw" } })).rejects.toThrow(); await expect(db.bookingIdempotency.create({ data: { id: randomUUID(), capabilityHash: hash(f.created.cookie), commandKey: randomUUID(), payloadHash: "a".repeat(64), appointmentId: "test", result: { rawManagementToken: "forbidden" }, expiresAt: new Date() } })).rejects.toThrow(); });
 it("different concurrent command keys still create only one appointment", async () => { const f = await fixture(), r = await f.ready(); const results = await Promise.all([f.api.confirm(f.created.cookie, randomUUID(), r.payloadHash, r.version), f.api.confirm(f.created.cookie, randomUUID(), r.payloadHash, r.version)]); expect(results.filter(x => x.ok)).toHaveLength(1); expect(await db.appointment.count({ where: { serviceId: f.serviceId } })).toBe(1); });
 it("rolls appointment and idempotency back when confirmation persistence fails", async () => { const f = await fixture(), r = await f.ready(); const failing: DraftRepository = { ...repo, transaction: (cap, work) => repo.transaction(cap, tx => work({ ...tx, saveIdempotency: async () => { throw new Error("synthetic failure"); } })) }; const api = new BookingDrafts(failing, { now: f.now, id: randomUUID, token: generateManagementToken, hash }); expect((await api.confirm(f.created.cookie, randomUUID(), r.payloadHash, r.version)).ok).toBe(false); expect(await db.appointment.count({ where: { serviceId: f.serviceId } })).toBe(0); expect((await f.api.read(f.created.cookie)).ok).toBe(true); });
 it("revalidates inactive service and rejects arbitrary mode before persistence", async () => { const f = await fixture(), r = await f.ready(); expect((await f.api.change(f.created.cookie, r.version, { type: "mode", meetingMode: "ONLINE" })).ok).toBe(false); await db.service.update({ where: { id: f.serviceId }, data: { active: false } }); expect((await f.api.confirm(f.created.cookie, randomUUID(), r.payloadHash, r.version)).ok).toBe(false); expect((await f.api.read(f.created.cookie)).ok).toBe(true); });
 it("bounded cleanup deletes expired PII but preserves refreshed drafts", async () => { const f = await fixture(); await db.bookingDraft.updateMany({ where: { capabilityHash: hash(f.created.cookie) }, data: { expiresAt: new Date("2020-01-01") } }); expect(await repo.purge(new Date("2020-01-02"), 1)).toBe(1); expect((await f.api.read(f.created.cookie)).ok).toBe(false); const alive = await fixture(); expect(await repo.purge(new Date("2020-01-02"), 1)).toBe(0); expect((await alive.api.read(alive.created.cookie)).ok).toBe(true); });

});
