import "dotenv/config";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@/generated/prisma/client";
import { reserveAppointment } from "@/modules/appointments/application/booking";
import { appointmentWriter } from "@/modules/appointments/infrastructure/prisma-appointments";
import { generateManagementToken } from "@/modules/appointments/infrastructure/management-token";
import { bookingNotificationPlanner } from "@/modules/notifications/infrastructure/planner";
import { aesSecretBox } from "@/modules/notifications/infrastructure/secret-box";
import type { SecretBox } from "@/modules/notifications/application/ports";
import { profileDetails, serviceDetails } from "../fixtures/catalog";
const connectionString = process.env.TEST_DATABASE_URL;
if (!connectionString || !new URL(connectionString).pathname.endsWith("_test")) throw new Error("Separate TEST_DATABASE_URL required");
const db = new PrismaClient({ adapter: new PrismaPg({ connectionString, max: 10 }) });
const box = aesSecretBox(randomBytes(32).toString("base64"));
const profileIds: string[] = [], userIds: string[] = [];
const baseNow = Date.parse("2027-01-01T00:00:00Z");
async function fixture(options: { start?: string; now?: number; encryption?: SecretBox } = {}) {
 const profileId = randomUUID(), serviceId = randomUUID(); profileIds.push(profileId);
 await db.advisorProfile.create({ data: { id: profileId, ...profileDetails, notificationEmail: `${profileId}@example.test`, status: "ACTIVE", services: { create: { ...serviceDetails, id: serviceId, active: true } }, weeklyAvailability: { create: Array.from({ length: 7 }, (_, i) => ({ id: randomUUID(), weekday: i + 1, startMinute: 0, endMinute: 1440 })) } } });
 const now = options.now ?? baseNow;
 const result = await db.$transaction(async tx => { const result = await reserveAppointment(appointmentWriter(tx), { primaryProfileId: profileId, serviceId, participantIds: [profileId], startUtc: options.start ?? "2027-01-06T08:00:00Z", meetingMode: "PHONE", customer: { firstName: "Synthetic", lastName: "Customer", email: "customer@example.test", phone: "123", address: null, remarks: "PRIVATE-FREETEXT" }, guests: ["guest@example.test"] }, { now: () => now, id: randomUUID, token: generateManagementToken }); await bookingNotificationPlanner(options.encryption ?? box)(tx, result.appointmentId, result.rawManagementToken, now); return result; });
 return { ...result, profileId, serviceId, now };
}

import { CustomerManagement } from "@/modules/appointments/application/customer-management";
import { prismaCustomerManagement, purgeCustomerReceipts } from "@/modules/appointments/infrastructure/prisma-customer-management";
const hash = (raw: string) => createHash("sha256").update(raw).digest("hex");
const hashes: string[] = [];
function api(now = baseNow) { return new CustomerManagement(prismaCustomerManagement(db), () => now, hash); }
async function setup() { const f = await fixture(); hashes.push(hash(f.rawManagementToken)); return f; }
afterEach(async () => { await db.$transaction(async tx => {
 await tx.appointmentMutationReceipt.deleteMany({ where: { capabilityHash: { in: hashes } } });
 const where = { appointment: { service: { advisorProfileId: { in: profileIds } } } };
 await tx.notification.deleteMany({ where }); await tx.appointmentReservation.deleteMany({ where }); await tx.appointmentGuest.deleteMany({ where }); await tx.appointmentParticipant.deleteMany({ where }); await tx.appointment.deleteMany({ where: { service: { advisorProfileId: { in: profileIds } } } });
 await tx.profileRelation.deleteMany({ where: { sourceProfileId: { in: profileIds } } });
 await tx.weeklyAvailability.deleteMany({ where: { advisorProfileId: { in: profileIds } } }); await tx.service.deleteMany({ where: { advisorProfileId: { in: profileIds } } }); await tx.advisorProfile.deleteMany({ where: { id: { in: profileIds } } }); await tx.user.deleteMany({ where: { id: { in: userIds } } });
 }); hashes.length = 0; profileIds.length = 0; userIds.length = 0; });
afterAll(() => db.$disconnect());
describe("customer appointment management", () => {
 it("retains guest privacy information when cancellation replaces an unsent first invitation", async () => { const f = await setup(); await api().change(f.rawManagementToken, randomUUID(), { type: "cancel", version: 0 }); const notification = await db.notification.findFirstOrThrow({ where: { appointmentId: f.appointmentId, type: "BOOKING_CANCELLED", recipientCategory: "GUEST" } }); expect(notification.payload).toMatchObject({ guestSource: "CUSTOMER" }); });

 it("rechecks every actual advisor and preserves both reservations on collision", async () => { const f = await setup(), additional = await fixture({ start: "2027-01-07T09:00:00Z" }); await db.$transaction(async tx => { await tx.appointmentParticipant.create({ data: { id: randomUUID(), appointmentId: f.appointmentId, advisorProfileId: additional.profileId, role: "ADDITIONAL", profileName: "Second advisor", profileTitle: "Advisor" } }); await tx.appointmentReservation.create({ data: { id: randomUUID(), appointmentId: f.appointmentId, advisorProfileId: additional.profileId, startAt: new Date(f.startUtc), endAt: new Date(f.endUtc) } }); }); await expect(api().change(f.rawManagementToken, randomUUID(), { type: "reschedule", version: 0, startUtc: "2027-01-07T09:00:00Z", meetingMode: "PHONE" })).rejects.toMatchObject({ code: "CONFLICT" }); expect(await db.appointmentReservation.count({ where: { appointmentId: f.appointmentId } })).toBe(2); });

 it("expires replay receipts and purges them in bounded batches", async () => { const f = await setup(), key = randomUUID(); await api().change(f.rawManagementToken, key, { type: "cancel", version: 0 }); await expect(api(baseNow + 86400000).change(f.rawManagementToken, key, { type: "cancel", version: 0 })).rejects.toMatchObject({ code: "NOT_FOUND" }); await purgeCustomerReceipts(db, baseNow + 86400000); expect(await db.appointmentMutationReceipt.count({ where: { capabilityHash: hash(f.rawManagementToken) } })).toBe(0); });

 it("uses current offered meeting data only for an explicit mode change", async () => { const f = await setup(); await db.service.update({ where: { id: f.serviceId }, data: { meetingModePolicy: "CLIENT_CHOICE", allowedMeetingModes: ["PHONE", "ONLINE"], onlineUrl: "https://video.example.test/room", onlineProvider: "Test Video" } }); await api().change(f.rawManagementToken, randomUUID(), { type: "reschedule", version: 0, startUtc: f.startUtc, meetingMode: "ONLINE" }); const a = await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } }); expect(a.onlineUrl).toBe("https://video.example.test/room"); expect(a.phoneDirection).toBeNull(); expect(a.calendarSequence).toBe(1); });
 it("rejects target after availability changes without releasing original reservation", async () => { const f = await setup(); await db.weeklyAvailability.deleteMany({ where: { advisorProfileId: f.profileId } }); await expect(api().change(f.rawManagementToken, randomUUID(), { type: "reschedule", version: 0, startUtc: "2027-01-07T09:00:00Z", meetingMode: "PHONE" })).rejects.toMatchObject({ code: "CONFLICT" }); const a = await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId }, include: { reservations: true } }); expect(a.version).toBe(0); expect(a.reservations[0].startAt.toISOString()).toBe(f.startUtc); });
 it("does not issue an immediate reminder for a new start exactly 24 hours away", async () => { const f = await setup(); await api().change(f.rawManagementToken, randomUUID(), { type: "reschedule", version: 0, startUtc: "2027-01-02T00:00:00Z", meetingMode: "PHONE" }); expect(await db.notification.count({ where: { appointmentId: f.appointmentId, type: "REMINDER", status: "PENDING" } })).toBe(0); });
 it("rolls back when outbox planning fails after reservation changes", async () => { const f = await setup(); const original = await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } }); // The injected adapter fails precisely at notification insertion.
 const extension = db.$extends({ query: { notification: { createMany: async () => { throw new Error("synthetic outbox failure"); } } } });
 const service = new CustomerManagement(prismaCustomerManagement(extension as unknown as PrismaClient), () => baseNow, hash);
 await expect(service.change(f.rawManagementToken, randomUUID(), { type: "cancel", version: 0 })).rejects.toMatchObject({ code: "UNAVAILABLE" }); expect(await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } })).toEqual(original); expect(await db.appointmentReservation.count({ where: { appointmentId: f.appointmentId } })).toBe(1); });

 it("returns only appointment-specific customer information", async () => { const f = await setup(); const view = await api().read(f.rawManagementToken); expect(view.canChange).toBe(true); const json = JSON.stringify(view); for (const value of ["customer@example", "PRIVATE-FREETEXT", "guest@example", f.profileId, f.rawManagementToken]) expect(json).not.toContain(value); });
 it.each([86400000, 86399999])("blocks changes with %i milliseconds remaining", async remaining => { const f = await setup(); const now = Date.parse(f.startUtc) - remaining; await expect(api(now).change(f.rawManagementToken, randomUUID(), { type: "cancel", version: 0 })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(await db.appointmentReservation.count({ where: { appointmentId: f.appointmentId } })).toBe(1); });
 it("allows strictly more than 24 hours and revokes access on cancellation", async () => { const f = await setup(); const service = api(Date.parse(f.startUtc) - 86400001), key = randomUUID(); const first = await service.change(f.rawManagementToken, key, { type: "cancel", version: 0 }); expect(first).toEqual({ status: "CANCELLED", version: 1, replay: false }); expect(await service.change(f.rawManagementToken, key, { type: "cancel", version: 0 })).toEqual({ ...first, replay: true }); await expect(service.read(f.rawManagementToken)).rejects.toMatchObject({ code: "NOT_FOUND" }); await expect(service.change(f.rawManagementToken, randomUUID(), { type: "cancel", version: 0 })).rejects.toMatchObject({ code: "NOT_FOUND" }); expect(await db.appointmentReservation.count({ where: { appointmentId: f.appointmentId } })).toBe(0); expect(await db.notification.count({ where: { appointmentId: f.appointmentId, type: "BOOKING_CANCELLED" } })).toBe(3); });
 it("uses uniform unavailable responses for invalid, revoked and expired tokens", async () => { const f = await setup(); for (const token of ["invalid", "x".repeat(43)]) await expect(api().read(token)).rejects.toMatchObject({ code: "NOT_FOUND" }); await expect(api(Date.parse(f.endUtc)).read(f.rawManagementToken)).rejects.toMatchObject({ code: "NOT_FOUND" }); await db.appointment.update({ where: { id: f.appointmentId }, data: { managementTokenRevokedAt: new Date(baseNow) } }); await expect(api().read(f.rawManagementToken)).rejects.toMatchObject({ code: "NOT_FOUND" }); });
 it("preserves identity and snapshots on time change with inactive profile/service", async () => { const f = await setup(), before = await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } }); await db.advisorProfile.update({ where: { id: f.profileId }, data: { status: "INACTIVE" } }); await db.service.update({ where: { id: f.serviceId }, data: { active: false } }); const result = await api().change(f.rawManagementToken, randomUUID(), { type: "reschedule", version: 0, startUtc: "2027-01-07T09:00:00Z", meetingMode: "PHONE" }); expect(result.version).toBe(1); const after = await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } }); expect(after.calendarUid).toBe(before.calendarUid); expect(after.calendarSequence).toBe(1); expect(after.managementTokenHash).toBe(before.managementTokenHash); expect(after.managementTokenExpiresAt).toEqual(after.endAt); expect(after.phoneDirection).toBe(before.phoneDirection); expect(await db.notification.count({ where: { appointmentId: after.id, status: "PENDING", type: "BOOKING_CHANGED" } })).toBe(3); });
 it("leaves all state unchanged after collision", async () => { const f = await setup(); await db.$transaction(tx => reserveAppointment(appointmentWriter(tx), { primaryProfileId: f.profileId, serviceId: f.serviceId, participantIds: [f.profileId], startUtc: "2027-01-07T09:00:00Z", meetingMode: "PHONE", customer: { firstName: "Other", lastName: "Test", email: "other@example.test", phone: "123", address: null, remarks: null }, guests: [] }, { now: () => baseNow, id: randomUUID, token: generateManagementToken })); const before = await db.appointment.findUnique({ where: { id: f.appointmentId }, include: { reservations: true, notifications: true } }); await expect(api().change(f.rawManagementToken, randomUUID(), { type: "reschedule", version: 0, startUtc: "2027-01-07T09:00:00Z", meetingMode: "PHONE" })).rejects.toMatchObject({ code: "CONFLICT" }); expect(await db.appointment.findUnique({ where: { id: f.appointmentId }, include: { reservations: true, notifications: true } })).toEqual(before); });
 it("serializes concurrent reschedules and rejects the stale version", async () => { const f = await setup(); const results = await Promise.allSettled(["09", "10"].map(hour => api().change(f.rawManagementToken, randomUUID(), { type: "reschedule", version: 0, startUtc: `2027-01-07T${hour}:00:00Z`, meetingMode: "PHONE" }))); expect(results.filter(r => r.status === "fulfilled")).toHaveLength(1); expect(results.filter(r => r.status === "rejected")).toHaveLength(1); expect((await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } })).version).toBe(1); });
 it("keeps no-op requests event-free and rejects key reuse with different payload", async () => { const f = await setup(), key = randomUUID(); await api().change(f.rawManagementToken, key, { type: "reschedule", version: 0, startUtc: f.startUtc, meetingMode: "PHONE" }); expect((await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } })).calendarSequence).toBe(0); expect(await db.notification.count({ where: { appointmentId: f.appointmentId } })).toBe(6); await expect(api().change(f.rawManagementToken, key, { type: "cancel", version: 0 })).rejects.toMatchObject({ code: "CONFLICT" }); });
 it("rejects non-offered modes without changing reservations", async () => { const f = await setup(); await expect(api().change(f.rawManagementToken, randomUUID(), { type: "reschedule", version: 0, startUtc: f.startUtc, meetingMode: "ONLINE" })).rejects.toMatchObject({ code: "INVALID_INPUT" }); expect(await db.appointmentReservation.count({ where: { appointmentId: f.appointmentId } })).toBe(1); });
 it("offers own occupied slot while excluding unrelated appointments", async () => { const f = await setup(); const values = await api().slots(f.rawManagementToken, "2027-01-06"); expect(values.some(s => Date.parse(s.startUtc) === Date.parse(f.startUtc))).toBe(true); });
 it("rejects raw PII in replay receipts at the database boundary", async () => { const f = await setup(); await expect(db.appointmentMutationReceipt.create({ data: { id: randomUUID(), capabilityHash: hash(f.rawManagementToken), commandKey: randomUUID(), payloadHash: "a".repeat(64), expiresAt: new Date(baseNow + 86400000), result: { status: "CANCELLED", version: 1, email: "private@example.test" } } })).rejects.toThrow(); });
});
