import "dotenv/config";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@/generated/prisma/client";
import { reserveAppointment } from "@/modules/appointments/application/booking";
import { appointmentWriter } from "@/modules/appointments/infrastructure/prisma-appointments";
import { generateManagementToken } from "@/modules/appointments/infrastructure/management-token";
import { bookingNotificationPlanner } from "@/modules/notifications/infrastructure/planner";
import { aesSecretBox } from "@/modules/notifications/infrastructure/secret-box";
import type { SecretBox } from "@/modules/notifications/application/ports";
import { profileDetails, serviceDetails } from "../fixtures/catalog";
const connectionString = process.env.TEST_DATABASE_URL;
if (!connectionString || !new URL(connectionString).pathname.endsWith("_test")) throw new Error("Separate TEST_DATABASE_URL required");
const db = new PrismaClient({ adapter: new PrismaPg({ connectionString, max: 10 }) });
const box = aesSecretBox(randomBytes(32).toString("base64"));
const profileIds: string[] = [], userIds: string[] = [];
const baseNow = Date.parse("2027-01-01T00:00:00Z");
async function fixture(options: { start?: string; now?: number; encryption?: SecretBox } = {}) {
 const profileId = randomUUID(), serviceId = randomUUID(); profileIds.push(profileId);
 await db.advisorProfile.create({ data: { id: profileId, ...profileDetails, notificationEmail: `${profileId}@example.test`, status: "ACTIVE", services: { create: { ...serviceDetails, id: serviceId, active: true } }, weeklyAvailability: { create: Array.from({ length: 7 }, (_, i) => ({ id: randomUUID(), weekday: i + 1, startMinute: 0, endMinute: 1440 })) } } });
 const now = options.now ?? baseNow;
 const result = await db.$transaction(async tx => { const result = await reserveAppointment(appointmentWriter(tx), { primaryProfileId: profileId, serviceId, participantIds: [profileId], startUtc: options.start ?? "2027-01-06T08:00:00Z", meetingMode: "PHONE", customer: { firstName: "Synthetic", lastName: "Customer", email: "customer@example.test", phone: "123", address: null, remarks: "PRIVATE-FREETEXT" }, guests: ["guest@example.test"] }, { now: () => now, id: randomUUID, token: generateManagementToken }); await bookingNotificationPlanner(options.encryption ?? box)(tx, result.appointmentId, result.rawManagementToken, now); return result; });
 return { ...result, profileId, serviceId, now };
}

import { CustomerManagement } from "@/modules/appointments/application/customer-management";
import { prismaCustomerManagement } from "@/modules/appointments/infrastructure/prisma-customer-management";
const hash = (raw: string) => createHash("sha256").update(raw).digest("hex");
const hashes: string[] = [];
function api(now = baseNow) { return new CustomerManagement(prismaCustomerManagement(db), () => now, hash); }
async function setup() { const f = await fixture(); hashes.push(hash(f.rawManagementToken)); return f; }
afterEach(async () => { await db.$transaction(async tx => {
 await tx.internalAppointmentReceipt.deleteMany({ where: { actorId: { in: userIds } } });
 await tx.appointmentMutationReceipt.deleteMany({ where: { capabilityHash: { in: hashes } } });
 const where = { appointment: { service: { advisorProfileId: { in: profileIds } } } };
 await tx.notification.deleteMany({ where }); await tx.appointmentReservation.deleteMany({ where }); await tx.appointmentGuest.deleteMany({ where }); await tx.appointmentParticipant.deleteMany({ where }); await tx.appointment.deleteMany({ where: { service: { advisorProfileId: { in: profileIds } } } });
 await tx.profileRelation.deleteMany({ where: { sourceProfileId: { in: profileIds } } });
 await tx.weeklyAvailability.deleteMany({ where: { advisorProfileId: { in: profileIds } } }); await tx.service.deleteMany({ where: { advisorProfileId: { in: profileIds } } }); await tx.advisorProfile.deleteMany({ where: { id: { in: profileIds } } }); await tx.user.deleteMany({ where: { id: { in: userIds } } });
 }); hashes.length = 0; profileIds.length = 0; userIds.length = 0; });
afterAll(() => db.$disconnect());

import { prismaNotifications } from "@/modules/notifications/infrastructure/prisma-notifications";
import { InternalAppointments } from "@/modules/appointments/application/internal-management";
import { prismaInternalAppointments, purgeInternalReceipts } from "@/modules/appointments/infrastructure/prisma-internal-management";
async function user(role: "ADMIN" | "ADVISOR" = "ADMIN", profileId?: string) { const id = randomUUID(); userIds.push(id); await db.user.create({ data: { id, name: "Synthetic actor", email: `${id}@example.test`, role } }); if (profileId) await db.advisorProfile.update({ where: { id: profileId }, data: { userId: id } }); return id; }
function internal(now = baseNow) { return new InternalAppointments(prismaInternalAppointments(db, box), () => now, hash); }
describe("internal appointment application", () => {
 it("audits create, metadata, guests and resend without values; replay and no-op add no event", async () => {
   const f = await setup(), admin = await user(), key = randomUUID();
   expect(await db.auditLog.count({ where: { resourceId: f.appointmentId, action: "APPOINTMENT_CREATED" } })).toBe(1);
   const command = { type: "details" as const, version: 0, patch: { remarks: "SECRET-AUDIT-PROBE" } };
   await internal().change(admin, f.appointmentId, key, command); await internal().change(admin, f.appointmentId, key, command);
   await internal().change(admin, f.appointmentId, randomUUID(), { ...command, version: 1 });
   expect(await db.auditLog.count({ where: { resourceId: f.appointmentId } })).toBe(2);
   await internal().change(admin, f.appointmentId, randomUUID(), { type: "guests", version: 1, emails: [] });
   await internal().change(admin, f.appointmentId, randomUUID(), { type: "resend", version: 2 });
   const rows = await db.auditLog.findMany({ where: { resourceId: f.appointmentId } });
   expect(rows).toHaveLength(4); const serialized = JSON.stringify(rows);
   for (const secret of ["SECRET-AUDIT-PROBE", "customer@example.test", "guest@example.test", f.rawManagementToken]) expect(serialized).not.toContain(secret);
   expect(rows.find(r => r.action === "APPOINTMENT_GUESTS_CHANGED")?.recipientCount).toBe(3);
   expect(rows.find(r => r.action === "CONFIRMATION_RESENT")?.recipientCount).toBe(1);
 });
 it("refreshes an unsent initial confirmation without losing its encrypted customer link", async () => { const f = await setup(), admin = await user(); const message = await db.notification.findFirstOrThrow({ where: { appointmentId: f.appointmentId, type: "BOOKING_CONFIRMATION", recipientCategory: "CUSTOMER" } }); await internal().change(admin, f.appointmentId, randomUUID(), { type: "reschedule", version: 0, startUtc: "2027-01-07T09:00:00Z", meetingMode: "PHONE" }); const leaseToken = randomUUID(); await db.notification.update({ where: { id: message.id }, data: { leaseToken, leaseUntil: new Date(baseNow + 120000), attempts: 1 } }); const prepared = await prismaNotifications(db, box).prepare({ id: message.id, leaseToken, attempts: 1 }, new Date(baseNow)); expect(prepared?.secret).toBe(f.rawManagementToken); expect(prepared?.payload.calendar).toMatchObject({ sequence: 1, startUtc: "2027-01-07T09:00:00.000Z" }); });

 it("authorizes an actual additional advisor independently of the primary", async () => { const f = await setup(), extra = await fixture({ start: "2027-01-07T08:00:00Z" }), advisor = await user("ADVISOR", extra.profileId); await db.$transaction(async tx => { await tx.appointmentParticipant.create({ data: { id: randomUUID(), appointmentId: f.appointmentId, advisorProfileId: extra.profileId, role: "ADDITIONAL", profileName: "Additional", profileTitle: "Advisor" } }); await tx.appointmentReservation.create({ data: { id: randomUUID(), appointmentId: f.appointmentId, advisorProfileId: extra.profileId, startAt: new Date(f.startUtc), endAt: new Date(f.endUtc) } }); }); expect((await internal().detail(advisor, f.appointmentId)).id).toBe(f.appointmentId); await internal().change(advisor, f.appointmentId, randomUUID(), { type: "details", version: 0, patch: { firstName: "Updated" } }); expect((await internal().detail(advisor, f.appointmentId)).version).toBe(1); });
 it("allows an internal cancellation inside 24h and purges expired command receipts", async () => { const f = await setup(), admin = await user(), now = Date.parse(f.startUtc) - 1; await internal(now).change(admin, f.appointmentId, randomUUID(), { type: "cancel", version: 0 }); expect((await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } })).status).toBe("CANCELLED"); await purgeInternalReceipts(db, now + 86400000); expect(await db.internalAppointmentReceipt.count({ where: { appointmentId: f.appointmentId } })).toBe(0); });
 it("rejects PII in receipts and an invalid guest source at the DB boundary", async () => { const f = await setup(), admin = await user(); await expect(db.internalAppointmentReceipt.create({ data: { id: randomUUID(), actorId: admin, appointmentId: f.appointmentId, action: "resend", commandKey: randomUUID(), payloadHash: "a".repeat(64), createdAt: new Date(baseNow), expiresAt: new Date(baseNow + 86400000), result: { status: "CONFIRMED", version: 1, noOp: false, secret: "forbidden" } } })).rejects.toThrow(); await expect(db.$executeRaw`UPDATE "AppointmentGuest" SET source = 'UNKNOWN' WHERE "appointmentId" = ${f.appointmentId}`).rejects.toThrow(); });

 it("reactivates only the unsent reminder when a removed guest is re-added before reminder time", async () => { const f = await setup(), admin = await user(); const reminder = await db.notification.findFirstOrThrow({ where: { appointmentId: f.appointmentId, recipientEmail: "guest@example.test", type: "REMINDER" } }); await internal().change(admin, f.appointmentId, randomUUID(), { type: "guests", version: 0, emails: [] }); await internal().change(admin, f.appointmentId, randomUUID(), { type: "guests", version: 1, emails: ["guest@example.test"] }); expect((await db.notification.findUniqueOrThrow({ where: { id: reminder.id } })).status).toBe("PENDING"); expect(await db.notification.count({ where: { appointmentId: f.appointmentId, recipientEmail: "guest@example.test", type: "REMINDER" } })).toBe(1); });
 it("provides internal slots inside 24 hours only after current authorization", async () => { const f = await setup(), advisor = await user("ADVISOR", f.profileId), now = Date.parse("2027-01-06T07:00:00Z"); expect((await internal(now).slots(advisor, f.appointmentId, "2027-01-06")).some(s => Date.parse(s.startUtc) === now)).toBe(true); await db.user.update({ where: { id: advisor }, data: { active: false } }); await expect(internal(now).slots(advisor, f.appointmentId, "2027-01-06")).rejects.toMatchObject({ code: "FORBIDDEN" }); });
 it("rolls back details when notification persistence fails", async () => { const f = await setup(), admin = await user(); const extended = db.$extends({ query: { notification: { createMany: async () => { throw new Error("synthetic failure"); } } } }); const service = new InternalAppointments(prismaInternalAppointments(extended as unknown as PrismaClient, box), () => baseNow, hash); await expect(service.change(admin, f.appointmentId, randomUUID(), { type: "details", version: 0, patch: { firstName: "Changed" } })).rejects.toMatchObject({ code: "UNAVAILABLE" }); expect((await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } })).version).toBe(0); expect(await db.internalAppointmentReceipt.count({ where: { appointmentId: f.appointmentId } })).toBe(0); });

 it("allows only active ADMIN or actual ADVISOR, including inactive participant profiles", async () => { const f = await setup(), admin = await user(), advisor = await user("ADVISOR", f.profileId); expect((await internal().detail(admin, f.appointmentId)).email).toBe("customer@example.test"); await db.advisorProfile.update({ where: { id: f.profileId }, data: { status: "INACTIVE" } }); expect((await internal().detail(advisor, f.appointmentId)).id).toBe(f.appointmentId); await db.user.update({ where: { id: advisor }, data: { active: false } }); await expect(internal().detail(advisor, f.appointmentId)).rejects.toMatchObject({ code: "FORBIDDEN" }); });
 it("does not grant access through ProfileRelation and filters calendar rows", async () => { const f = await setup(), other = await setup(), advisor = await user("ADVISOR", other.profileId); await db.profileRelation.create({ data: { id: randomUUID(), sourceProfileId: f.profileId, targetProfileId: other.profileId } }); await expect(internal().detail(advisor, f.appointmentId)).rejects.toMatchObject({ code: "NOT_FOUND" }); const page = await internal().list(advisor, "2027-01-06", "month"); expect(page.items.map(a => a.id)).toEqual([other.appointmentId]); expect(page.items[0]).not.toHaveProperty("email"); });
 it("paginates stable calendar results without exposing tokens", async () => { await setup(); await setup(); const admin = await user(); const first = await internal().list(admin, "2027-01-06", "day", 1); expect(first.items).toHaveLength(1); expect(first.next).not.toBeNull(); const second = await internal().list(admin, "2027-01-06", "day", 1, first.next!); expect(second.items[0].id).not.toBe(first.items[0].id); expect(JSON.stringify(await internal().detail(admin, first.items[0].id))).not.toContain("managementToken"); });
 it("updates only metadata without ICS, guest mail or replacement reminders", async () => { const f = await setup(), admin = await user(), reminders = await db.notification.findMany({ where: { appointmentId: f.appointmentId, type: "REMINDER" }, orderBy: { id: "asc" } }); await internal().change(admin, f.appointmentId, randomUUID(), { type: "details", version: 0, patch: { firstName: "Changed", remarks: "SECRET-FREE-TEXT" } }); const a = await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } }); expect(a.version).toBe(1); expect(a.calendarSequence).toBe(0); const mails = await db.notification.findMany({ where: { appointmentId: a.id, type: "BOOKING_CHANGED" } }); expect(mails).toHaveLength(2); for (const mail of mails) expect(mail.payload).toMatchObject({ method: null }); expect(JSON.stringify(mails)).not.toContain("SECRET-FREE-TEXT"); expect(await db.notification.findMany({ where: { appointmentId: a.id, type: "REMINDER" }, orderBy: { id: "asc" } })).toEqual(reminders); });
 it("updates term-specific meeting details and advances sequence once", async () => { const f = await setup(), admin = await user(); await internal().change(admin, f.appointmentId, randomUUID(), { type: "details", version: 0, patch: { phoneDirection: "CLIENT_CALLS_ADVISOR", advisorPhone: "+49 123" } }); const a = await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } }); expect(a.calendarSequence).toBe(1); expect(a.advisorPhone).toBe("+49 123"); });
 it("revalidates availability for metadata edits and leaves state unchanged", async () => { const f = await setup(), admin = await user(); await db.weeklyAvailability.deleteMany({ where: { advisorProfileId: f.profileId } }); await expect(internal().change(admin, f.appointmentId, randomUUID(), { type: "details", version: 0, patch: { firstName: "Changed" } })).rejects.toMatchObject({ code: "CONFLICT" }); expect((await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } })).version).toBe(0); });
 it("allows internal starts at now without the customer 24h restriction", async () => { const f = await setup(), admin = await user(), now = Date.parse("2027-01-05T09:00:00Z"); await internal(now).change(admin, f.appointmentId, randomUUID(), { type: "reschedule", version: 0, startUtc: new Date(now).toISOString(), meetingMode: "PHONE" }); expect((await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } })).startAt.getTime()).toBe(now); expect(await db.notification.count({ where: { appointmentId: f.appointmentId, type: "REMINDER", status: "PENDING" } })).toBe(0); });
 it("allows metadata on an already started but unfinished appointment", async () => { const f = await setup(), admin = await user(); await internal(Date.parse(f.startUtc) + 1).change(admin, f.appointmentId, randomUUID(), { type: "details", version: 0, patch: { phone: "456" } }); expect((await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } })).phone).toBe("456"); });
 it("rejects past starts, forbidden fields and foreign recipients", async () => { const f = await setup(), admin = await user(); await expect(internal().change(admin, f.appointmentId, randomUUID(), { type: "reschedule", version: 0, startUtc: "2026-12-31T08:00:00Z", meetingMode: "PHONE" })).rejects.toThrow(); await expect(internal().change(admin, f.appointmentId, randomUUID(), { type: "details", version: 0, patch: { email: "other@example.test" } } as never)).rejects.toMatchObject({ code: "INVALID_INPUT" }); await expect(internal().change(admin, f.appointmentId, randomUUID(), { type: "resend", version: 0, recipients: ["foreign@example.test"] })).rejects.toMatchObject({ code: "INVALID_INPUT" }); });
 it("sends removed guests only their CANCEL and new guests their own invitation", async () => { const f = await setup(), admin = await user(); await internal().change(admin, f.appointmentId, randomUUID(), { type: "guests", version: 0, emails: ["new@example.test"] }); const a = await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId }, include: { guests: true } }); expect(a.status).toBe("CONFIRMED"); expect(a.calendarSequence).toBe(1); expect(a.guests[0].source).toBe("INTERNAL"); const cancelled = await db.notification.findMany({ where: { appointmentId: a.id, type: "BOOKING_CANCELLED", status: "PENDING" } }); expect(cancelled.map(n => n.recipientEmail)).toEqual(["guest@example.test"]); expect(cancelled[0].removedGuest).toBe(true); const added = await db.notification.findFirstOrThrow({ where: { appointmentId: a.id, recipientEmail: "new@example.test", type: "BOOKING_CONFIRMATION" } }); expect(added.payload).toMatchObject({ guestSource: "INTERNAL", method: "REQUEST" }); await api().change(f.rawManagementToken, randomUUID(), { type: "reschedule", version: 1, startUtc: "2027-01-07T09:00:00Z", meetingMode: "PHONE" }); expect((await db.notification.findUniqueOrThrow({ where: { id: cancelled[0].id } })).status).toBe("PENDING"); });
 it("does not create a late reminder for a newly added guest", async () => { const f = await setup(), admin = await user(); await internal(Date.parse(f.startUtc) - 86400000).change(admin, f.appointmentId, randomUUID(), { type: "guests", version: 0, emails: ["guest@example.test", "late@example.test"] }); expect(await db.notification.count({ where: { appointmentId: f.appointmentId, recipientEmail: "late@example.test", type: "REMINDER" } })).toBe(0); });
 it("rotates the customer capability on resend with stable UID/sequence and no new reminder", async () => { const f = await setup(), admin = await user(), before = await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } }), key = randomUUID(); const result = await internal().change(admin, f.appointmentId, key, { type: "resend", version: 0 }); const after = await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } }); expect(after.calendarUid).toBe(before.calendarUid); expect(after.calendarSequence).toBe(0); expect(after.managementTokenHash).not.toBe(before.managementTokenHash); await expect(api().read(f.rawManagementToken)).rejects.toMatchObject({ code: "NOT_FOUND" }); expect(await db.notification.count({ where: { appointmentId: f.appointmentId, type: "REMINDER" } })).toBe(3); expect(await internal().change(admin, f.appointmentId, key, { type: "resend", version: 0 })).toEqual({ ...result, replay: true }); });
 it("limits resend across actors and rejects replay after role deactivation", async () => { const f = await setup(), admin = await user(), second = await user(); for (let version = 0; version < 3; version++) await internal().change(version % 2 ? second : admin, f.appointmentId, randomUUID(), { type: "resend", version, recipients: [f.profileId + "@example.test"] }); await expect(internal().change(second, f.appointmentId, randomUUID(), { type: "resend", version: 3 })).rejects.toMatchObject({ code: "FORBIDDEN" }); const key = randomUUID(); await internal(baseNow + 600000).change(admin, f.appointmentId, key, { type: "resend", version: 3 }); await db.user.update({ where: { id: admin }, data: { active: false } }); await expect(internal(baseNow + 600000).change(admin, f.appointmentId, key, { type: "resend", version: 3 })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
 it.each(["COMPLETED", "NO_SHOW"] as const)("sets %s only at end and never changes calendar sequence or sends mail", async status => { const f = await setup(), admin = await user(); await expect(internal(Date.parse(f.endUtc) - 1).change(admin, f.appointmentId, randomUUID(), { type: "outcome", version: 0, status })).rejects.toThrow(); const result = await internal(Date.parse(f.endUtc)).change(admin, f.appointmentId, randomUUID(), { type: "outcome", version: 0, status }); expect(result.status).toBe(status); expect((await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } })).calendarSequence).toBe(0); expect(await db.appointmentReservation.count({ where: { appointmentId: f.appointmentId } })).toBe(0); expect(await db.notification.count({ where: { appointmentId: f.appointmentId } })).toBe(6); expect((await internal(Date.parse(f.endUtc)).change(admin, f.appointmentId, randomUUID(), { type: "outcome", version: 0, status })).noOp).toBe(true); await expect(internal(Date.parse(f.endUtc)).change(admin, f.appointmentId, randomUUID(), { type: "outcome", version: 1, status: status === "COMPLETED" ? "NO_SHOW" : "COMPLETED" })).rejects.toThrow(); });
 it("serializes competing internal mutations", async () => { const f = await setup(), first = await user(), second = await user(); const result = await Promise.allSettled([first, second].map((actor, i) => internal().change(actor, f.appointmentId, randomUUID(), { type: "details", version: 0, patch: { firstName: `Changed ${i}` } }))); expect(result.filter(r => r.status === "fulfilled")).toHaveLength(1); expect(result.filter(r => r.status === "rejected")).toHaveLength(1); });
 it("keeps original reminders for a customer mode-only change", async () => { const f = await setup(); await db.service.update({ where: { id: f.serviceId }, data: { meetingModePolicy: "CLIENT_CHOICE", allowedMeetingModes: ["PHONE", "ONLINE"], onlineProvider: "Video", onlineUrl: "https://video.example.test" } }); const before = await db.notification.findMany({ where: { appointmentId: f.appointmentId, type: "REMINDER" }, orderBy: { id: "asc" } }); await api().change(f.rawManagementToken, randomUUID(), { type: "reschedule", version: 0, startUtc: f.startUtc, meetingMode: "ONLINE" }); expect(await db.notification.findMany({ where: { appointmentId: f.appointmentId, type: "REMINDER" }, orderBy: { id: "asc" } })).toEqual(before); });
});
