import "dotenv/config";
import { randomBytes, randomUUID } from "node:crypto";
import { afterAll, afterEach, describe, expect, it, vi } from "vitest";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@/generated/prisma/client";
import { reserveAppointment } from "@/modules/appointments/application/booking";
import { appointmentWriter } from "@/modules/appointments/infrastructure/prisma-appointments";
import { generateManagementToken } from "@/modules/appointments/infrastructure/management-token";
import { NotificationWorker } from "@/modules/notifications/application/worker";
import { prismaNotifications } from "@/modules/notifications/infrastructure/prisma-notifications";
import { bookingNotificationPlanner, queueEvent, mailInclude, appointmentRecipients } from "@/modules/notifications/infrastructure/planner";
import { aesSecretBox, secretContext } from "@/modules/notifications/infrastructure/secret-box";
import type { Mail, SecretBox } from "@/modules/notifications/application/ports";
import { profileDetails, serviceDetails } from "../fixtures/catalog";
const connectionString = process.env.TEST_DATABASE_URL;
if (!connectionString || !new URL(connectionString).pathname.endsWith("_test")) throw new Error("Separate TEST_DATABASE_URL required");
const db = new PrismaClient({ adapter: new PrismaPg({ connectionString, max: 10 }) });
const box = aesSecretBox(randomBytes(32).toString("base64")), repo = prismaNotifications(db, box);
const profileIds: string[] = [], userIds: string[] = [];
const baseNow = Date.parse("2025-01-01T00:00:00Z"); // Earlier than other suites' fixtures; worker claims cannot consume them.
const config = { publicOrigin: "https://booking.example.test", from: "sender@example.test", guestPrivacyUrl: "https://booking.example.test/privacy/guests" };
async function fixture(options: { start?: string; now?: number; encryption?: SecretBox } = {}) {
 const profileId = randomUUID(), serviceId = randomUUID(); profileIds.push(profileId);
 await db.advisorProfile.create({ data: { id: profileId, ...profileDetails, notificationEmail: `${profileId}@example.test`, status: "ACTIVE", services: { create: { ...serviceDetails, id: serviceId, active: true } }, weeklyAvailability: { create: Array.from({ length: 7 }, (_, i) => ({ id: randomUUID(), weekday: i + 1, startMinute: 0, endMinute: 1440 })) } } });
 const now = options.now ?? baseNow;
 const result = await db.$transaction(async tx => { const result = await reserveAppointment(appointmentWriter(tx), { primaryProfileId: profileId, serviceId, participantIds: [profileId], startUtc: options.start ?? "2025-01-06T08:00:00Z", meetingMode: "PHONE", customer: { firstName: "Synthetic", lastName: "Customer", email: "customer@example.test", phone: "123", address: null, remarks: "PRIVATE-FREETEXT" }, guests: ["guest@example.test"] }, { now: () => now, id: randomUUID, token: generateManagementToken }); await bookingNotificationPlanner(options.encryption ?? box)(tx, result.appointmentId, result.rawManagementToken, now); return result; });
 return { ...result, profileId, serviceId, now };
}
function worker(now: () => number, send: (mail: Mail) => Promise<void> = async () => {}) { return new NotificationWorker(repo, { send }, config, now, { emit: vi.fn() }); }
afterEach(async () => { await db.$transaction(async tx => {
 const where = { appointment: { service: { advisorProfileId: { in: profileIds } } } };
 await tx.notification.deleteMany({ where }); await tx.appointmentReservation.deleteMany({ where }); await tx.appointmentGuest.deleteMany({ where }); await tx.appointmentParticipant.deleteMany({ where }); await tx.appointment.deleteMany({ where: { service: { advisorProfileId: { in: profileIds } } } });
 await tx.profileRelation.deleteMany({ where: { sourceProfileId: { in: profileIds } } });
 await tx.weeklyAvailability.deleteMany({ where: { advisorProfileId: { in: profileIds } } }); await tx.service.deleteMany({ where: { advisorProfileId: { in: profileIds } } }); await tx.advisorProfile.deleteMany({ where: { id: { in: profileIds } } }); await tx.user.deleteMany({ where: { id: { in: userIds } } });
 }); profileIds.length = 0; userIds.length = 0; });
afterAll(() => db.$disconnect());
describe("transactional notification outbox", () => {
 it("commits per-recipient confirmation/reminders with only encrypted customer capability", async () => { const f = await fixture(); const rows = await db.notification.findMany({ where: { appointmentId: f.appointmentId } }); expect(rows).toHaveLength(6); const secret = rows.find(n => n.secretCipher)!; expect(secret.recipientCategory).toBe("CUSTOMER"); expect(rows.filter(n => n.secretCipher)).toHaveLength(1); expect(JSON.stringify(rows).includes(f.rawManagementToken)).toBe(false); expect(JSON.stringify(rows)).not.toContain("PRIVATE-FREETEXT"); expect(box.open(secret.secretCipher!, secretContext(secret.id, f.appointmentId, secret.recipientEmail)) === f.rawManagementToken).toBe(true); expect(secret.secretExpiresAt!.getTime()).toBe(baseNow + 86400000); });
 it("rolls the booking back if encryption/outbox planning fails", async () => { const broken: SecretBox = { seal: () => { throw new Error("synthetic encryption failure"); }, open: () => "" }; await expect(fixture({ encryption: broken })).rejects.toThrow(); expect(await db.appointment.count({ where: { service: { advisorProfileId: { in: profileIds } } } })).toBe(0); expect(await db.notification.count({ where: { appointment: { service: { advisorProfileId: { in: profileIds } } } } })).toBe(0); });
 it("does not enqueue an immediate reminder at exactly 24h lead", async () => { const f = await fixture({ start: "2025-01-02T00:00:00Z" }); expect(await db.notification.count({ where: { appointmentId: f.appointmentId, type: "REMINDER" } })).toBe(0); });
 it("planning the same event twice creates no duplicate jobs or generations", async () => { const f = await fixture(); await db.$transaction(tx => bookingNotificationPlanner(box)(tx, f.appointmentId, f.rawManagementToken, baseNow)); expect(await db.notification.count({ where: { appointmentId: f.appointmentId } })).toBe(6); expect((await db.appointment.findUniqueOrThrow({ where: { id: f.appointmentId } })).notificationEventNumber).toBe(1); });
 it("two workers lease each due recipient once and clear sent secrets", async () => { const f = await fixture(), sent: Mail[] = []; const send = async (mail: Mail) => { sent.push(mail); }; await Promise.all([worker(() => baseNow, send).run(10), worker(() => baseNow, send).run(10)]); expect(sent).toHaveLength(3); expect(new Set(sent.map(m => m.id)).size).toBe(3); expect(sent.filter(m => m.text.includes("manage#token="))).toHaveLength(1); expect(sent.every(m => !m.ics?.includes(f.rawManagementToken))).toBe(true); expect(await db.notification.count({ where: { appointmentId: f.appointmentId, status: "SENT" } })).toBe(3); expect(await db.notification.count({ where: { appointmentId: f.appointmentId, secretCipher: { not: null } } })).toBe(0); });
 it("reclaims expired leases and fences stale completion", async () => { await fixture(); const first = await repo.claim(new Date(baseNow), 10, 30000); expect(first).toHaveLength(3); expect(await repo.claim(new Date(baseNow + 29999), 10, 30000)).toHaveLength(0); const second = await repo.claim(new Date(baseNow + 30000), 10, 30000); expect(second).toHaveLength(3); expect(await repo.finish(first[0], new Date(baseNow + 30001), true)).toBe(false); const current = second.find(x => x.id === first[0].id)!; expect(await repo.finish(current, new Date(baseNow + 30001), true)).toBe(true); });
 it("retries after 1/5/30/120/360 minutes then marks FAILED with safe error", async () => { const f = await fixture(); let now = baseNow; const w = worker(() => now, async () => { throw new Error("PROVIDER-SECRET-MUST-NOT-PERSIST"); }); const delays = [1, 5, 30, 120, 360]; for (let i = 0; i < 6; i++) { await w.run(10); const rows = await db.notification.findMany({ where: { appointmentId: f.appointmentId, type: "BOOKING_CONFIRMATION" } }); expect(rows.every(n => n.attempts === i + 1 && n.lastErrorCode === "DELIVERY_FAILED")).toBe(true); if (i < 5) { expect(rows[0].dueAt.getTime()).toBe(now + delays[i] * 60000); expect(await repo.claim(new Date(rows[0].dueAt.getTime() - 1), 10, 30000)).toHaveLength(0); now = rows[0].dueAt.getTime(); } else expect(rows.every(n => n.status === "FAILED")).toBe(true); } });
 it("purges secret material at expiry and prevents later secret resend", async () => { const f = await fixture(); expect(await repo.purgeSecrets(new Date(baseNow + 86400000), 100)).toBe(1); const row = await db.notification.findFirstOrThrow({ where: { appointmentId: f.appointmentId, requiresSecret: true } }); expect(row).toMatchObject({ status: "FAILED", secretCipher: null, secretTokenHash: null, secretExpiresAt: null, lastErrorCode: "SECRET_EXPIRED" }); });
 it("reminders use current projection and omit a removed guest", async () => { const f = await fixture(); await worker(() => baseNow).run(); await db.appointmentGuest.deleteMany({ where: { appointmentId: f.appointmentId } }); await db.appointment.update({ where: { id: f.appointmentId }, data: { serviceName: "Updated snapshot" } }); const sent: Mail[] = []; await worker(() => Date.parse(f.startUtc) - 86400000, async m => { sent.push(m); }).run(); expect(sent).toHaveLength(2); expect(sent.every(m => m.text.includes("Updated snapshot") && m.to !== "guest@example.test")).toBe(true); });
 it("never sends reminders after appointment start", async () => { const f = await fixture(); await worker(() => baseNow).run(); const sent = vi.fn(async () => {}); await worker(() => Date.parse(f.startUtc), sent).run(); expect(sent).not.toHaveBeenCalled(); });
 it("cancelled appointment suppresses old confirmations and sends only cancellation events", async () => { const f = await fixture(); await db.$transaction(async tx => { await tx.appointmentReservation.deleteMany({ where: { appointmentId: f.appointmentId } }); const a = await tx.appointment.update({ where: { id: f.appointmentId }, data: { status: "CANCELLED", calendarSequence: 1, notificationEventNumber: 2, managementTokenRevokedAt: new Date(baseNow) }, include: mailInclude }); await queueEvent(tx, a, { eventId: randomUUID(), type: "BOOKING_CANCELLED", recipients: appointmentRecipients(a), now: baseNow, method: "CANCEL" }); }); const sent: Mail[] = []; const w = worker(() => baseNow, async m => { sent.push(m); }); await w.run(); await w.run(); expect(sent).toHaveLength(3); expect(sent.every(m => m.method === "CANCEL")).toBe(true); });
 it("removed guest gets only their explicit cancellation, other recipients keep REQUEST", async () => { const f = await fixture(); await db.$transaction(async tx => { const old = await tx.appointment.findUniqueOrThrow({ where: { id: f.appointmentId }, include: mailInclude }); await tx.appointmentGuest.deleteMany({ where: { appointmentId: f.appointmentId } }); const a = await tx.appointment.update({ where: { id: f.appointmentId }, data: { notificationEventNumber: 2, calendarSequence: 1 }, include: mailInclude }); await queueEvent(tx, { ...old, notificationEventNumber: 2, calendarSequence: 1 }, { eventId: randomUUID(), type: "BOOKING_CANCELLED", recipients: [{ email: "guest@example.test", category: "GUEST", advisorProfileId: null }], now: baseNow, method: "CANCEL", removedGuest: true }); await queueEvent(tx, a, { eventId: randomUUID(), type: "BOOKING_CHANGED", recipients: appointmentRecipients(a), now: baseNow }); }); const sent: Mail[] = [], w = worker(() => baseNow, async m => { sent.push(m); }); await w.run(); await w.run(); expect(sent.filter(m => m.method === "CANCEL").map(m => m.to)).toEqual(["guest@example.test"]); expect(sent.filter(m => m.to === "guest@example.test")).toHaveLength(1); });
 it("preserves per-recipient event order while earlier mail is leased", async () => { const f = await fixture(); await db.$transaction(async tx => { const a = await tx.appointment.update({ where: { id: f.appointmentId }, data: { notificationEventNumber: 2 }, include: mailInclude }); await queueEvent(tx, a, { eventId: randomUUID(), type: "BOOKING_CHANGED", recipients: appointmentRecipients(a), now: baseNow, method: null }); }); const first = await repo.claim(new Date(baseNow), 10, 30000); expect(first).toHaveLength(3); expect(await repo.claim(new Date(baseNow), 10, 30000)).toHaveLength(0); for (const n of first) await repo.finish(n, new Date(baseNow), true); expect(await repo.claim(new Date(baseNow), 10, 30000)).toHaveLength(3); });
 it("protects retries with current ADMIN rights and rejects expired secrets", async () => { const f = await fixture(); const id = randomUUID(); userIds.push(id); await db.user.create({ data: { id, name: "Test", email: `${id}@example.test`, role: "ADVISOR" } }); const n = await db.notification.findFirstOrThrow({ where: { appointmentId: f.appointmentId, requiresSecret: true } }); await db.notification.update({ where: { id: n.id }, data: { status: "FAILED" } }); await expect(repo.retryFailed(id, n.id, new Date(baseNow))).rejects.toMatchObject({ code: "FORBIDDEN" }); await db.user.update({ where: { id }, data: { role: "ADMIN" } }); await repo.retryFailed(id, n.id, new Date(baseNow)); expect((await db.notification.findUniqueOrThrow({ where: { id: n.id } })).status).toBe("PENDING"); await repo.purgeSecrets(new Date(baseNow + 86400000), 100); await expect(repo.retryFailed(id, n.id, new Date(baseNow + 86400000))).rejects.toMatchObject({ code: "CONFLICT" }); });
 it("database rejects secrets on guests, invalid leases and attempt overflow", async () => { const f = await fixture(); const n = await db.notification.findFirstOrThrow({ where: { appointmentId: f.appointmentId, requiresSecret: true } }); await expect(db.notification.update({ where: { id: n.id }, data: { recipientCategory: "GUEST" } })).rejects.toThrow(); await expect(db.notification.update({ where: { id: n.id }, data: { leaseToken: "unpaired" } })).rejects.toThrow(); await expect(db.notification.update({ where: { id: n.id }, data: { attempts: 7 } })).rejects.toThrow(); await expect(db.notification.update({ where: { id: n.id }, data: { secretCipher: null } })).rejects.toThrow(); });
 it("simultaneous event planning remains idempotent under the appointment lock", async () => { const f = await fixture(); await Promise.all([db.$transaction(tx => bookingNotificationPlanner(box)(tx, f.appointmentId, f.rawManagementToken, baseNow)), db.$transaction(tx => bookingNotificationPlanner(box)(tx, f.appointmentId, f.rawManagementToken, baseNow))]); expect(await db.notification.count({ where: { appointmentId: f.appointmentId } })).toBe(6); });
 it("exhausted abandoned leases become visible failures instead of a seventh attempt", async () => { const f = await fixture(); const row = await db.notification.findFirstOrThrow({ where: { appointmentId: f.appointmentId, type: "BOOKING_CONFIRMATION" } }); await db.notification.update({ where: { id: row.id }, data: { attempts: 6, leaseToken: randomUUID(), leaseUntil: new Date(baseNow - 1) } }); const jobs = await repo.claim(new Date(baseNow), 10, 30000); expect(jobs.some(n => n.id === row.id)).toBe(false); expect((await db.notification.findUniqueOrThrow({ where: { id: row.id } })).lastErrorCode).toBe("LEASE_EXHAUSTED"); expect((await repo.metrics()).failed).toBe(1); });

 it("includes actual additional advisors but excludes unselected relations", async () => { const a = await fixture(), b = await fixture(), unrelated = await fixture(); await db.profileRelation.createMany({ data: [b.profileId, unrelated.profileId].map(targetProfileId => ({ id: randomUUID(), sourceProfileId: a.profileId, targetProfileId })) }); const booked = await db.$transaction(async tx => { const result = await reserveAppointment(appointmentWriter(tx), { primaryProfileId: a.profileId, serviceId: a.serviceId, participantIds: [a.profileId, b.profileId], startUtc: "2025-01-07T08:00:00Z", meetingMode: "PHONE", customer: { firstName: "A", lastName: "B", email: "customer@example.test", phone: "123", address: null, remarks: null }, guests: ["guest@example.test"] }, { now: () => baseNow, id: randomUUID, token: generateManagementToken }); await bookingNotificationPlanner(box)(tx, result.appointmentId, result.rawManagementToken, baseNow); return result; }); const rows = await db.notification.findMany({ where: { appointmentId: booked.appointmentId, type: "BOOKING_CONFIRMATION" } }); expect(rows).toHaveLength(4); expect(rows.filter(n => n.recipientCategory === "ADVISOR").map(n => n.advisorProfileId).sort()).toEqual([a.profileId, b.profileId].sort()); expect(rows.some(n => n.advisorProfileId === unrelated.profileId)).toBe(false); });
 it("supersedes queued capability mail after token rotation", async () => { const f = await fixture(); await db.appointment.update({ where: { id: f.appointmentId }, data: { managementTokenHash: generateManagementToken().hash } }); const sent: Mail[] = []; await worker(() => baseNow, async mail => { sent.push(mail); }).run(); expect(sent.some(m => m.to === "customer@example.test")).toBe(false); expect(await db.notification.count({ where: { appointmentId: f.appointmentId, secretCipher: { not: null } } })).toBe(0); });
 it("does not deliver obsolete reminder generations", async () => { const f = await fixture(); await worker(() => baseNow).run(); await db.appointment.update({ where: { id: f.appointmentId }, data: { reminderGeneration: { increment: 1 } } }); const sent = vi.fn(async () => {}); await worker(() => Date.parse(f.startUtc) - 86400000, sent).run(); expect(sent).not.toHaveBeenCalled(); });

});
