/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import {useEffect,useState} from "react";import styles from "./booking.module.css";
type Profile={id:string;name:string;title:string;shortDescription:string};type Service={id:string;name:string;description:string;durationMinutes:number;allowedMeetingModes:string[]};type Slot={startUtc:string;endUtc:string;localDate:string;localTime:string;offset:string};type Draft={payload:any;version:number;expiresAt:string};
const steps=["Beratung","Leistung","Teilnehmende","Termin","Modus","Kontaktdaten","PrÃƒÂ¼fen"];
async function json(url:string,init?:RequestInit){const r=await fetch(url,init),x=await r.json();if(!r.ok||x.ok===false)throw new Error(x.error?.message??x.error??"Anfrage fehlgeschlagen.");return x.value??x}
export function BookingWizard(){
 const [step,setStep]=useState(0),[profiles,setProfiles]=useState<Profile[]>([]),[services,setServices]=useState<Service[]>([]),[options,setOptions]=useState<any>(null),[slots,setSlots]=useState<Slot[]>([]),[draft,setDraft]=useState<Draft|null>(null),[review,setReview]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[success,setSuccess]=useState<any>(null);
 useEffect(()=>{json("/api/public/catalog").then(setProfiles).catch(e=>setError(e.message));fetch("/api/booking/draft").then(async r=>r.ok?(await r.json()).value:null).then(d=>{if(d)setDraft(d)}).catch(()=>{})},[]);
 async function ensureDraft(){if(draft)return draft;const d=await json("/api/booking/draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create"})});setDraft(d);return d}
 async function change(command:any){setBusy(true);setError("");try{const d=await ensureDraft();const n=await json("/api/booking/draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"change",version:d.version,command})});setDraft(n);return n}catch(e:any){setError(e.message);throw e}finally{setBusy(false)}}
 async function primary(id:string){try{await change({type:"primary",profileId:id});const [s,o]=await Promise.all([json("/api/public/catalog?profile="+encodeURIComponent(id)),json("/api/public/catalog?kind=participants&profile="+encodeURIComponent(id))]);setServices(s);setOptions(o);setStep(1)}catch{}}
 async function service(id:string){try{const d=await change({type:"service",serviceId:id});setStep(2);if(!options&&d.payload.primaryProfileId)setOptions(await json("/api/public/catalog?kind=participants&profile="+encodeURIComponent(d.payload.primaryProfileId)))}catch{}}
 async function participants(ids:string[]){try{await change({type:"participants",participantIds:ids});setStep(3)}catch{}}
 async function loadSlots(date:string){try{const d=await change({type:"date",date});const p=d.payload;setSlots(await json("/api/public/availability?primary="+encodeURIComponent(p.primaryProfileId)+"&service="+encodeURIComponent(p.serviceId)+"&date="+date+"&participants="+p.participantIds.map(encodeURIComponent).join(",")))}catch{}}
 async function slot(s:Slot){try{await change({type:"slot",startUtc:s.startUtc});setStep(4)}catch{}}
 async function mode(m:string){try{await change({type:"mode",meetingMode:m});setStep(5)}catch{}}
 async function customer(fd:FormData){try{let d=await change({type:"customer",customer:{firstName:fd.get("firstName"),lastName:fd.get("lastName"),email:fd.get("email"),phone:fd.get("phone"),address:fd.get("address")||null,remarks:fd.get("remarks")||null}});const guests=String(fd.get("guests")??"").split(",").map(x=>x.trim()).filter(Boolean);if(guests.length)d=await change({type:"guests",guests});const x=await json("/api/booking/draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"review"})});setReview(x);setDraft(d);setStep(6)}catch{}}
 async function confirm(){if(!review||!draft)return;setBusy(true);setError("");try{const x=await json("/api/booking/draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"confirm",version:draft.version,payloadHash:review.payloadHash,commandKey:crypto.randomUUID().replaceAll("-","")})});setSuccess(x)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(success)return <section id="booking" className={styles.wizard} aria-live="polite"><h2>Termin erfolgreich gebucht</h2><p>Ihre TerminbestÃƒÂ¤tigung wird per E-Mail versendet.</p><p><strong>Terminnummer:</strong> {success.appointmentId}</p><p>Sie kÃƒÂ¶nnen dieses Fenster jetzt schlieÃƒÅ¸en. Ãƒâ€žnderungen erfolgen ÃƒÂ¼ber den sicheren Link in Ihrer BestÃƒÂ¤tigungs-E-Mail.</p></section>;
 const p=draft?.payload;
 return <section id="booking" className={styles.wizard}><nav className={styles.progress} aria-label="Buchungsfortschritt"><ol>{steps.map((s,i)=><li key={s} aria-current={i===step?"step":undefined}>{i+1}. {s}</li>)}</ol></nav>{error&&<p className={styles.error} role="alert">{error}</p>}
 {step===0&&<div><h2>Beratung auswÃƒÂ¤hlen</h2><div className={styles.grid}>{profiles.map(x=><button disabled={busy} className={styles.choice} key={x.id} onClick={()=>primary(x.id)}><strong>{x.name}</strong><br/>{x.title}<br/><small>{x.shortDescription}</small></button>)}</div></div>}
 {step===1&&<div><h2>Leistung auswÃƒÂ¤hlen</h2><div className={styles.grid}>{services.map(x=><button disabled={busy} className={styles.choice} key={x.id} onClick={()=>service(x.id)}><strong>{x.name}</strong><br/>{x.description}<br/>{x.durationMinutes} Minuten</button>)}</div></div>}
 {step===2&&options&&<Participants options={options} busy={busy} submit={participants}/>}
 {step===3&&<div><h2>Datum und Uhrzeit</h2><label className={styles.field}>Datum<input type="date" min={new Date().toISOString().slice(0,10)} onChange={e=>loadSlots(e.target.value)}/></label><div className={styles.grid}>{slots.map(s=><button className={styles.choice} key={s.startUtc} onClick={()=>slot(s)}>{s.localTime} Uhr <small>({s.offset})</small></button>)}</div>{slots.length===0&&p?.date&&<p>FÃƒÂ¼r dieses Datum sind keine freien Zeiten verfÃƒÂ¼gbar.</p>}</div>}
 {step===4&&<div><h2>Terminart</h2><div className={styles.grid}>{(services.find(x=>x.id===p?.serviceId)?.allowedMeetingModes??[]).map(m=><button className={styles.choice} key={m} onClick={()=>mode(m)}>{m==="IN_PERSON"?"Vor Ort":m==="PHONE"?"Telefon":"Online"}</button>)}</div></div>}
 {step===5&&<div><h2>Kontaktdaten</h2><div className={styles.notice}><strong>Datenschutzhinweis vor der Dateneingabe</strong><p>Die folgenden Angaben werden zur DurchfÃƒÂ¼hrung und Kommunikation Ihres Termins verarbeitet. Pflichtfelder sind fÃƒÂ¼r die Terminabwicklung erforderlich; optionale Angaben kÃƒÂ¶nnen leer bleiben. Details, Rechtsgrundlagen, EmpfÃƒÂ¤nger und Aufbewahrung werden in der <a href="/datenschutz">Datenschutzinformation</a> beschrieben. Die Betreiberangaben und finalen Rechtstexte mÃƒÂ¼ssen vor Produktionsstart freigegeben sein.</p></div><form action={customer}><label className={styles.field}>Vorname *<input name="firstName" required maxLength={100}/></label><label className={styles.field}>Nachname *<input name="lastName" required maxLength={100}/></label><label className={styles.field}>E-Mail *<input name="email" type="email" required maxLength={254}/></label><label className={styles.field}>Telefon *<input name="phone" type="tel" required maxLength={32}/></label><label className={styles.field}>Adresse (optional)<input name="address" maxLength={500}/></label><label className={styles.field}>Bemerkungen (optional)<textarea name="remarks" maxLength={2000}/></label><label className={styles.field}>GÃƒÂ¤ste-E-Mails (optional, mit Komma trennen)<input name="guests"/></label><button disabled={busy} className={styles.button}>Weiter zur PrÃƒÂ¼fung</button></form></div>}
 {step===6&&review&&<div><h2>Angaben prÃƒÂ¼fen</h2><dl className={styles.summary}><dt>Leistung</dt><dd>{review.service.name} Ã‚Â· {review.service.durationMinutes} Minuten</dd><dt>Teilnehmende</dt><dd>{review.participants.map((x:any)=>x.name).join(", ")}</dd><dt>Termin</dt><dd>{new Intl.DateTimeFormat("de-DE",{dateStyle:"full",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(review.payload.startUtc))}</dd><dt>Terminart</dt><dd>{review.payload.meetingMode}</dd><dt>Name</dt><dd>{review.payload.customer.firstName} {review.payload.customer.lastName}</dd><dt>E-Mail</dt><dd>{review.payload.customer.email}</dd></dl><button disabled={busy} className={styles.button} onClick={confirm}>Termin verbindlich buchen</button></div>}
 {step>0&&step<6&&<div className={styles.actions}><button className={styles.button+" "+styles.secondary} onClick={()=>setStep(Math.max(0,step-1))}>ZurÃƒÂ¼ck</button></div>}</section>
}
function Participants({options,busy,submit}:{options:any,busy:boolean,submit:(ids:string[])=>void}){const fixed=[options.primary,...options.requiredParticipants].map((x:any)=>x.id),[ids,setIds]=useState<string[]>(()=>[...new Set([...fixed,...options.options.filter((x:any)=>x.defaultSelected).map((x:any)=>x.profile.id)])]);return <div><h2>Teilnehmende</h2><p>{options.primary.name} nimmt immer teil.</p><div className={styles.grid}>{options.options.map((o:any)=><label className={styles.choice} key={o.profile.id}><input type="checkbox" checked={ids.includes(o.profile.id)} disabled={!o.clientCanRemove} onChange={e=>setIds(e.target.checked?[...new Set([...ids,o.profile.id])]:ids.filter(x=>x!==o.profile.id))}/>{o.profile.name}{!o.clientCanRemove&&" (erforderlich)"}</label>)}</div><div className={styles.actions}><button disabled={busy} className={styles.button} onClick={()=>submit([...new Set([...fixed,...ids])])}>Weiter</button></div></div>}
