import Link from "next/link";import {headers} from "next/headers";import {notFound} from "next/navigation";import {internalAppointmentApi} from "@/shared/web/internal-appointments";import {appointmentAction} from "./actions";import styles from "../../internal.module.css";
export const dynamic="force-dynamic";
export default async function AppointmentDetail({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{updated?:string}>}){
 const {id}=await params,q=await searchParams,api=await internalAppointmentApi(await headers());let a;try{a=await api.detail(id)}catch{return notFound()}const action=appointmentAction.bind(null,id);
 return <main id="main" className={styles.main}><p><Link href="/internal/appointments">← Zur Terminübersicht</Link></p><section className={styles.hero}><h1>Termin: {a.firstName} {a.lastName}</h1>{q.updated&&<p role="status" className={styles.success}>Änderung wurde gespeichert.</p>}<div className={styles.meta}><span className={styles.status}>{a.status}</span><span>Version {a.version}</span></div></section>
 <section className={styles.panel}><h2>Termindetails</h2><dl><dt>Leistung</dt><dd>{a.serviceName}</dd><dt>Beginn</dt><dd>{new Intl.DateTimeFormat("de-DE",{dateStyle:"full",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(a.startUtc))}</dd><dt>Ende</dt><dd>{new Intl.DateTimeFormat("de-DE",{dateStyle:"full",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(a.endUtc))}</dd><dt>Modus</dt><dd>{a.meetingMode}</dd><dt>E-Mail</dt><dd>{a.email}</dd><dt>Bemerkung</dt><dd>{a.remarks||"—"}</dd></dl></section>
 {a.status==="CONFIRMED"&&<><section className={styles.panel}><h2>Termin bearbeiten</h2><form action={action} className={styles.toolbar}><input type="hidden" name="version" value={a.version}/><label className={styles.field}>Neuer Beginn (UTC)<input name="startUtc" type="datetime-local" required/></label><label className={styles.field}>Modus<select name="meetingMode" defaultValue={a.meetingMode}><option value="IN_PERSON">Vor Ort</option><option value="PHONE">Telefon</option><option value="ONLINE">Online</option></select></label><button className={styles.button} name="action" value="reschedule">Umbuchen</button></form>
 <form action={action} className={styles.toolbar}><input type="hidden" name="version" value={a.version}/><label className={styles.field}>Gäste (E-Mail, Komma-getrennt)<input name="emails" defaultValue={a.guests.map(g=>g.email).join(", ")}/></label><button className={styles.button} name="action" value="guests">Gäste speichern</button></form>
 <form action={action} className={styles.toolbar}><input type="hidden" name="version" value={a.version}/><label className={styles.field}>Bemerkung<input name="remarks" defaultValue={a.remarks??""}/></label><button className={styles.button} name="action" value="details">Details speichern</button></form></section>
 <section className={styles.panel}><h2>Weitere Aktionen</h2><form action={action} className={styles.toolbar}><input type="hidden" name="version" value={a.version}/><button className={styles.button} name="action" value="resend">Bestätigung erneut senden</button><button className={styles.button} name="action" value="cancel">Termin absagen</button><button className={styles.button} name="action" value="complete">Als abgeschlossen markieren</button><button className={styles.button} name="action" value="no-show">Als nicht erschienen markieren</button></form></section></>}</main>
}
