import { describe, expect, it, vi } from "vitest";
import { changeDraft, emptyDraft, bookingInput, assertLive, assertVersion, DRAFT_TTL } from "@/modules/booking/domain/draft";
import { draftHttp, draftCookie, readDraftCookie } from "@/modules/booking/infrastructure/draft-http";
import type { BookingDrafts } from "@/modules/booking/application/drafts";
const customer = { firstName: "A", lastName: "B", email: "a@example.test", phone: "123", address: null, remarks: null };
const full = () => ({ ...emptyDraft(), primaryProfileId: "p1", serviceId: "s1", participantIds: ["p1", "p2"], meetingMode: "PHONE" as const, date: "2026-10-05", startUtc: "2026-10-05T07:00:00Z", customer, guests: ["g@example.test"] });
describe("server draft state", () => {
 it("primary selection clears all dependent data", () => expect(changeDraft(full(), { type: "primary", profileId: "p3" })).toEqual({ ...emptyDraft(), primaryProfileId: "p3", participantIds: ["p3"] }));
 it("service change clears participants, mode, date and slot", () => expect(changeDraft(full(), { type: "service", serviceId: "s2" })).toMatchObject({ serviceId: "s2", participantIds: ["p1"], meetingMode: null, date: null, startUtc: null, customer }));
 it("participants change invalidates date and slot", () => expect(changeDraft(full(), { type: "participants", participantIds: ["p1"] })).toMatchObject({ date: null, startUtc: null }));
 it("date change invalidates slot", () => expect(changeDraft(full(), { type: "date", date: "2026-10-06" })).toMatchObject({ date: "2026-10-06", startUtc: null }));
 it.each(["2026-10-06T07:00:00Z", "2026-10-05T07:00:00", "2026-10-05T07:00:00.0001Z"])("rejects invalid slot %s", startUtc => expect(() => changeDraft(full(), { type: "slot", startUtc })).toThrow());
 it("uses concrete modes and requires complete review data", () => { expect(() => changeDraft(full(), { type: "mode", meetingMode: "CLIENT_CHOICE" as never })).toThrow(); expect(() => bookingInput(emptyDraft())).toThrow(); expect(bookingInput(full()).participantIds).toEqual(["p1", "p2"]); });
 it("rejects duplicate participants and customer guests", () => { expect(() => changeDraft(full(), { type: "participants", participantIds: ["p1", "p1"] })).toThrow(); expect(() => changeDraft(full(), { type: "guests", guests: [customer.email] })).toThrow(); });
 it("expires exactly at idle boundary and checks expected version", () => { const d = { id: "d", capabilityHash: "hash", payload: emptyDraft(), version: 2, expiresAt: new Date(DRAFT_TTL) }; expect(() => assertLive(d, DRAFT_TTL - 1)).not.toThrow(); expect(() => assertLive(d, DRAFT_TTL)).toThrow(); expect(() => assertVersion(d, 1)).toThrow(); });
});
describe("draft HTTP boundary", () => {
 const make = () => { const api = { read: vi.fn().mockResolvedValue({ ok: false, error: { code: "NOT_FOUND" } }), create: vi.fn().mockResolvedValue({ ok: true, value: { cookie: "a".repeat(43), payload: emptyDraft(), version: 0 } }), change: vi.fn(), review: vi.fn() }; return { api, handle: draftHttp(api as unknown as BookingDrafts, "https://booking.example.test", true) }; };
 const post = (body: unknown, origin = "https://booking.example.test") => new Request("https://booking.example.test/api/booking/draft", { method: "POST", headers: { origin, "content-type": "application/json" }, body: JSON.stringify(body) });
 it("uses host-only secure HttpOnly cookies and excludes capability from JSON", async () => { const { handle } = make(); const r = await handle(post({ action: "create" })); expect(r.status).toBe(201); expect(r.headers.get("set-cookie")).toContain("__Host-booking-draft="); expect(r.headers.get("set-cookie")).toContain("HttpOnly; SameSite=Lax; Max-Age=86400; Secure"); expect(JSON.stringify(await r.json()).includes("a".repeat(43))).toBe(false); });
 it.each(["https://evil.example.test", "null", ""])("rejects untrusted origin %s", async origin => { const { handle, api } = make(); expect((await handle(post({ action: "create" }, origin))).status).toBe(403); expect(api.create).not.toHaveBeenCalled(); });
 it("GET reads without mutation and sets private headers", async () => { const { handle, api } = make(); const r = await handle(new Request("https://booking.example.test/api/booking/draft?action=create")); expect(api.create).not.toHaveBeenCalled(); expect(r.headers.get("cache-control")).toBe("no-store"); expect(r.headers.get("referrer-policy")).toBe("no-referrer"); });
 it("rejects arbitrary draft IDs, duplicate cookies and unavailable confirm action", async () => { const req = new Request("https://example.test", { headers: { cookie: "__Host-booking-draft=a; __Host-booking-draft=b" } }); expect(readDraftCookie(req, true)).toBe(""); const { handle } = make(); expect((await handle(post({ action: "confirm", draftId: "foreign" }))).status).toBe(400); });
 it("bounds request size and requires JSON", async () => { const { handle } = make(); expect((await handle(post({ data: "x".repeat(33000) }))).status).toBe(413); expect((await handle(new Request("https://booking.example.test", { method: "POST", headers: { origin: "https://booking.example.test" }, body: "action=create" }))).status).toBe(415); });
 it("uses development cookie without weakening production cookie", () => { expect(draftCookie("test", false)).not.toContain("Secure"); expect(draftCookie("test", true)).toContain("Secure"); });
});
