import nodemailer from "nodemailer";
import { randomBytes } from "node:crypto";
import { createServer } from "node:net";
import { describe, expect, it } from "vitest";
import { renderIcs } from "@/modules/notifications/domain/icalendar";
import { calendarProjection, payloadFor, recipients, reminderAt, retryAt } from "@/modules/notifications/domain/notification";
import { composeMail } from "@/modules/notifications/application/worker";
import { aesSecretBox } from "@/modules/notifications/infrastructure/secret-box";
import { mailConfiguration } from "@/modules/notifications/infrastructure/config";
import { smtpConfiguration, smtpMessage, smtpTransport } from "@/modules/notifications/infrastructure/smtp";
const now = new Date("2026-10-01T00:00:00Z"), config = { publicOrigin: "https://booking.example.test", from: "sender@example.test", guestPrivacyUrl: "https://booking.example.test/privacy/guests" };
const a = { id: "appointment", calendarUid: "stable-id", calendarSequence: 3, startAt: new Date("2026-10-25T00:30:00Z"), endAt: new Date("2026-10-25T01:00:00Z"), serviceName: "Beratung", email: "customer@example.test", meetingMode: "PHONE" as const, phoneDirection: "ADVISOR_CALLS_CLIENT" as const, advisorPhone: null, placeName: null, visitAddress: null, onlineUrl: null, onlineProvider: null, phone: "PRIVATE-PHONE", remarks: "PRIVATE-REMARKS" };
const guest = { email: "guest@example.test", category: "GUEST" as const, advisorProfileId: null };
describe("calendar and recipient privacy", () => {
 it.each(["REQUEST", "CANCEL"] as const)("renders interoperable %s UTC event identity", method => { const ics = renderIcs(calendarProjection(a), method, config.from, guest.email, now); expect(ics).toContain(`METHOD:${method}`); expect(ics).toContain("UID:stable-id"); expect(ics).toContain("SEQUENCE:3"); expect(ics).toContain("DTSTART:20261025T003000Z"); expect(ics).toContain("DTEND:20261025T010000Z"); expect(ics).not.toContain("PRIVATE"); expect(ics).not.toContain(a.email); expect(ics.split("ATTENDEE;")).toHaveLength(2); });
 it("folds UTF-8 by octets and escapes content injection", () => { const crlf = String.fromCharCode(13, 10); const p = { ...calendarProjection(a), summary: "é".repeat(100) + crlf + "ATTENDEE:evil@example.test;comma," }; const ics = renderIcs(p, "REQUEST", config.from, guest.email, now); expect(ics.split(crlf).every(line => Buffer.byteLength(line, "utf8") <= 75)).toBe(true); expect(ics.split(crlf).filter(line => line.startsWith("ATTENDEE"))).toHaveLength(1); const unfolded = ics.split(crlf + " ").join(""); expect(unfolded).toContain(String.fromCharCode(92) + "nATTENDEE:"); expect(unfolded).toContain(String.fromCharCode(92) + ";"); });
 it("preserves distinct autumn instants", () => { const first = renderIcs(calendarProjection(a), "REQUEST", config.from, guest.email, now), second = renderIcs(calendarProjection({ ...a, startAt: new Date("2026-10-25T01:30:00Z"), endAt: new Date("2026-10-25T02:00:00Z") }), "REQUEST", config.from, guest.email, now); expect(first).toContain("DTSTART:20261025T003000Z"); expect(second).toContain("DTSTART:20261025T013000Z"); });
 it("rejects header injection in organizer", () => expect(() => renderIcs(calendarProjection(a), "REQUEST", "bad" + String.fromCharCode(13, 10) + "ATTENDEE:x@example.test", guest.email, now)).toThrow());
 it("deduplicates addresses with customer precedence", () => { const result = recipients("same@EXAMPLE.TEST", [{ id: "p", email: "same@example.test" }, { id: "q", email: "advisor@example.test" }], ["guest@example.test"]); expect(result).toHaveLength(3); expect(result.find(r => r.email === "same@example.test")?.category).toBe("CUSTOMER"); });
 it("gives guests source and privacy information without secrets or private contacts", () => { const mail = composeMail({ id: "n", type: "BOOKING_CONFIRMATION", recipient: guest, payload: payloadFor(a, "BOOKING_CONFIRMATION", guest), secret: null }, config, now); expect(mail.text).toContain("buchenden Person"); expect(mail.text).toContain(config.guestPrivacyUrl); expect(JSON.stringify(mail)).not.toContain("PRIVATE"); expect(mail.text).not.toContain("manage#"); });
 it("includes customer capability only in customer message and never ICS", () => { const recipient = { ...guest, category: "CUSTOMER" as const }; const mail = composeMail({ id: "n", type: "BOOKING_CONFIRMATION", recipient, payload: payloadFor(a, "BOOKING_CONFIRMATION", recipient), secret: "synthetic-secret" }, config, now); expect(mail.text).toContain("manage#token=synthetic-secret"); expect(mail.ics).not.toContain("synthetic-secret"); expect(() => composeMail({ id: "n", type: "BOOKING_CONFIRMATION", recipient: guest, payload: payloadFor(a, "BOOKING_CONFIRMATION", guest), secret: "synthetic-secret" }, config, now)).toThrow(); });
 it("renders password reset only for the internal USER recipient and without ICS", () => {
  const recipient = { email: "internal@example.test", category: "USER" as const, advisorProfileId: null };
  const mail = composeMail({ id: "reset", type: "PASSWORD_RESET", recipient, payload: { calendar: null, method: null, guestSource: null, text: "Passwort zuruecksetzen" }, secret: "https://booking.example.test/reset-password?token=synthetic" }, config, now);
  expect(mail.text).toContain("Passwort zuruecksetzen: https://booking.example.test/reset-password?token=synthetic");
  expect(mail.ics).toBeNull(); expect(mail.text).not.toContain("manage#");
 });
 it("describes internal guest source accurately", () => expect(payloadFor(a, "BOOKING_CONFIRMATION", guest, "REQUEST", "INTERNAL").guestSource).toBe("INTERNAL"));
 it("plain metadata and reminder messages omit calendar attachments", () => { const mail = composeMail({ id: "n", type: "REMINDER", recipient: guest, payload: payloadFor(a, "REMINDER", guest, null), secret: null }, config, now); expect(mail.ics).toBeNull(); expect(mail.text).toContain(a.serviceName); });
});
describe("retry, reminder and encrypted capability", () => {
 it.each([1, 5, 30, 120, 360])("schedules retry %i minutes", minutes => { const index = [1, 5, 30, 120, 360].indexOf(minutes); expect(retryAt(index + 1, 1000)?.getTime()).toBe(1000 + minutes * 60000); });
 it("ends after the fifth retry and enforces strict reminder boundary", () => { expect(retryAt(6, 0)).toBeNull(); expect(reminderAt(new Date(86400000), 0)).toBeNull(); expect(reminderAt(new Date(86400001), 0)?.getTime()).toBe(1); expect(reminderAt(new Date(86399999), 0)).toBeNull(); });
 it("encrypts nondeterministically and binds ciphertext to its notification", () => { const box = aesSecretBox(randomBytes(32).toString("base64")), x = box.seal("synthetic", "one"), y = box.seal("synthetic", "one"); expect(x === y || x.includes("synthetic")).toBe(false); expect(box.open(x, "one")).toBe("synthetic"); expect(() => box.open(x, "two")).toThrow(); expect(() => aesSecretBox("bad-key")).toThrow(); expect(() => aesSecretBox(randomBytes(32).toString("base64")).open(x, "one")).toThrow(); });
});
describe("delivery configuration", () => {
 it("requires production TLS and approved guest information", () => { const env = { NODE_ENV: "production" as const, MAIL_HOST: "localhost", MAIL_PORT: "587", MAIL_FROM: config.from, BETTER_AUTH_URL: config.publicOrigin, GUEST_PRIVACY_URL: config.guestPrivacyUrl }; expect(smtpConfiguration(env).allowLocalPlaintext).toBe(false); expect(() => mailConfiguration(env)).toThrow(); expect(mailConfiguration({ ...env, PRIVACY_INFORMATION_APPROVED: "true" })).toEqual(config); expect(() => mailConfiguration({ ...env, PRIVACY_INFORMATION_APPROVED: "true", GUEST_PRIVACY_URL: "http://evil.example.test" })).toThrow(); });
 it("uses stable message identity and disables external attachment reads", () => { const message = smtpMessage({ id: "notification-id", to: guest.email, subject: "Test", text: "Test", ics: "BEGIN:VCALENDAR", method: "REQUEST" }, config.from); expect(message.to).toEqual({ name: "", address: guest.email }); expect(message.messageId).toBe("<notification-id@example.test>"); expect(message.disableFileAccess && message.disableUrlAccess).toBe(true); expect(message).not.toHaveProperty("bcc"); expect(message.icalEvent?.method).toBe("REQUEST"); });
 it("delivers MIME and ICS to an isolated loopback SMTP listener", async () => {
  const crlf = String.fromCharCode(13, 10); let received = "";
  const server = createServer(socket => { let buffer = "", data = false; socket.write("220 localhost" + crlf); socket.on("data", chunk => { buffer += chunk.toString(); let index: number; while ((index = buffer.indexOf(crlf)) >= 0) { const line = buffer.slice(0, index); buffer = buffer.slice(index + 2); if (data) { if (line === ".") { data = false; socket.write("250 accepted" + crlf); } else received += line + crlf; } else if (line.startsWith("EHLO")) socket.write("250 localhost" + crlf); else if (line === "DATA") { data = true; socket.write("354 continue" + crlf); } else if (line === "QUIT") socket.end("221 bye" + crlf); else socket.write("250 ok" + crlf); } }); });
  await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve));
  try { const address = server.address(); if (!address || typeof address === "string") throw new Error("No loopback socket"); const mail = composeMail({ id: "smtp-test", type: "BOOKING_CONFIRMATION", recipient: guest, payload: payloadFor(a, "BOOKING_CONFIRMATION", guest), secret: null }, config, now); await smtpTransport({ host: "127.0.0.1", port: address.port, from: config.from, secure: false, allowLocalPlaintext: true }).send(mail); expect(received).toContain("text/calendar"); expect(received).toContain("method=REQUEST"); expect(received).not.toContain("PRIVATE"); }
  finally { await new Promise<void>(resolve => server.close(() => resolve())); }
 });
 it("never expands one address into an SMTP recipient list", async () => { const transport = nodemailer.createTransport({ jsonTransport: true }); const result = await transport.sendMail(smtpMessage({ id: "single-recipient", to: "first,second@example.test", subject: "Test", text: "Synthetic", ics: null, method: null }, config.from)); expect(result.envelope.to).toHaveLength(1); });

});
