"use server";
import {headers} from "next/headers";import {redirect} from "next/navigation";import {internalCatalog} from "@/shared/web/profile-catalog";import {internalAvailability} from "@/shared/web/availability";
const back=(id:string,msg?:string)=>redirect("/internal/admin/catalog/"+encodeURIComponent(id)+(msg?"?error="+encodeURIComponent(msg):"?updated=1"));
export async function catalogAction(id:string,formData:FormData){
 const api=await internalCatalog(await headers());if(!api)redirect("/login");const op=String(formData.get("operation")??""),v=Number(formData.get("version"));let r;
 if(op==="profile-status")r=await api.commands.setProfileStatus(api.actorId,id,v,String(formData.get("status"))==="ACTIVE"?"ACTIVE":"INACTIVE");
 else if(op==="profile-update")r=await api.commands.updateProfile(api.actorId,id,v,{name:String(formData.get("name")??""),title:String(formData.get("title")??""),shortDescription:String(formData.get("description")??""),notificationEmail:String(formData.get("email")??""),imageKey:null});
 else if(op==="public-presence")r=await api.commands.updatePublicPresence(api.actorId,id,v,{publicSlug:String(formData.get("publicSlug")??"")||null,aboutText:String(formData.get("aboutText")??"")||null,publicEmail:String(formData.get("publicEmail")??"")||null,publicPhone:String(formData.get("publicPhone")??"")||null,publicWebsite:String(formData.get("publicWebsite")??"")||null,publicAddress:String(formData.get("publicAddress")??"")||null,accentColor:String(formData.get("accentColor")??"")||null,showDvagPartners:formData.get("showDvagPartners")==="on",digitalCardEnabled:formData.get("digitalCardEnabled")==="on"});
 else if(op==="service-toggle")r=await api.commands.setServiceActive(api.actorId,id,String(formData.get("serviceId")),v,String(formData.get("active"))==="true");
 else if(op==="service-create")r=await api.commands.createService(api.actorId,id,{name:String(formData.get("name")??""),description:String(formData.get("description")??""),durationMinutes:Number(formData.get("duration")),meetingModePolicy:"CLIENT_CHOICE",allowedMeetingModes:["IN_PERSON"],placeName:String(formData.get("placeName")??""),visitAddress:String(formData.get("address")??""),phoneDirection:"ADVISOR_CALLS_CLIENT",advisorPhone:null,onlineUrl:null,onlineProvider:null},false);
 else if(op==="relation-create")r=await api.commands.createRelation(api.actorId,id,String(formData.get("targetId")??""),{active:true,proposedToClient:true,defaultSelected:false,clientCanRemove:true});
 else if(op==="relation-toggle")r=await api.commands.updateRelation(api.actorId,id,String(formData.get("targetId")),v,{active:String(formData.get("active"))==="true",proposedToClient:String(formData.get("proposed"))==="true",defaultSelected:String(formData.get("defaultSelected"))==="true",clientCanRemove:String(formData.get("removable"))==="true"});
 else if(op==="weekly-set"){const av=await internalAvailability(await headers());if(!av)return back(id,"Keine Berechtigung.");const start=String(formData.get("start")),end=String(formData.get("end")),minutes=(x:string)=>{const [h,m]=x.split(":").map(Number);return h*60+m},ranges=start&&end?[{start:minutes(start),end:minutes(end)}]:[];const x=await av.management.setWeeklyDay(av.actorId,id,v,Number(formData.get("weekday")),ranges);if(!x.ok)return back(id,x.error.message);if(x.value.status==="MERGE_REQUIRED")return back(id,"Ãœberschneidung erkannt. Bitte bestehende Ausnahmen zuerst prÃ¼fen.");return back(id);}
 else return back(id,"Unbekannte Aktion.");if(!r.ok)return back(id,r.error.message);back(id);
}
