import Link from "next/link";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { internalCatalog } from "@/shared/web/profile-catalog";
import { internalAvailability } from "@/shared/web/availability";
import { catalogAction } from "./actions";
import styles from "../../../internal.module.css";
export const dynamic="force-dynamic";
export default async function ProfileManagement({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{updated?:string,error?:string}>}){
 const {id}=await params,q=await searchParams,api=await internalCatalog(await headers());if(!api)redirect("/login");const result=await api.queries.getProfile(id);if(!result.ok||!result.value.aggregate)return <main className={styles.main}><p role="alert">Profil nicht gefunden.</p></main>;
 const {profile,services}=result.value.aggregate,relations=result.value.relations,availability=await internalAvailability(await headers()),weekly=availability?await availability.management.getWeeklyAvailability(availability.actorId,id):null,action=catalogAction.bind(null,id);
 return <main id="main" className={styles.main}><p><Link href="/internal/admin/catalog">← Profile</Link></p><section className={styles.hero}><h1>{profile.name}</h1><div className={styles.meta}><span>{profile.status}</span><span>Version {profile.version}</span></div>{q.updated&&<p role="status" className={styles.success}>Änderung gespeichert.</p>}{q.error&&<p role="alert" className={styles.error}>{q.error}</p>}
 {api.role==="ADMIN"&&<form action={action}><input type="hidden" name="operation" value="profile-status"/><input type="hidden" name="version" value={profile.version}/><input type="hidden" name="status" value={profile.status==="ACTIVE"?"INACTIVE":"ACTIVE"}/><button className={styles.button}>{profile.status==="ACTIVE"?"Profil deaktivieren":"Profil aktivieren"}</button></form>}</section>
 <section className={styles.panel}><h2>Leistungen</h2><div className={styles.grid}>{services.map(s=><article className={styles.card} key={s.id}><h3>{s.name}</h3><p>{s.description}</p><div className={styles.meta}><span>{s.durationMinutes} Minuten</span><span>{s.active?"Aktiv":"Inaktiv"}</span></div><form action={action}><input type="hidden" name="operation" value="service-toggle"/><input type="hidden" name="serviceId" value={s.id}/><input type="hidden" name="version" value={s.version}/><input type="hidden" name="active" value={String(!s.active)}/><button className={styles.button}>{s.active?"Deaktivieren":"Aktivieren"}</button></form></article>)}</div>
 <h3>Leistung anlegen</h3><form action={action} className={styles.toolbar}><input type="hidden" name="operation" value="service-create"/><label className={styles.field}>Name<input name="name" required/></label><label className={styles.field}>Beschreibung<input name="description" required/></label><label className={styles.field}>Dauer (Min.)<input name="duration" type="number" min="15" step="15" required/></label><label className={styles.field}>Ort<input name="placeName" required/></label><label className={styles.field}>Adresse<input name="address" required/></label><button className={styles.button}>Leistung anlegen</button></form></section>
 <section className={styles.panel}><h2>Beziehungen</h2>{relations.length?<ul>{relations.map(r=><li key={r.id}>{r.targetProfileId} · {r.active?"aktiv":"inaktiv"}</li>)}</ul>:<p>Keine Beziehungen.</p>}<form action={action} className={styles.toolbar}><input type="hidden" name="operation" value="relation-create"/><label className={styles.field}>Zielprofil-ID<input name="targetId" required/></label><button className={styles.button}>Beziehung anlegen</button></form></section>
 <section className={styles.panel}><h2>Wöchentliche Verfügbarkeit</h2>{!weekly||!weekly.ok?<p role="alert" className={styles.error}>{weekly&&!weekly.ok?weekly.error.message:"Nicht verfügbar."}</p>:<pre>{JSON.stringify(weekly.value,null,2)}</pre>}</section></main>
}
